// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

/**
 * Protobuf type {@code bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig}
 */
public  final class DanmuPlayerDynamicConfig extends
    com.google.protobuf.GeneratedMessageLite<
        DanmuPlayerDynamicConfig, DanmuPlayerDynamicConfig.Builder> implements
    // @@protoc_insertion_point(message_implements:bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig)
    DanmuPlayerDynamicConfigOrBuilder {
  private DanmuPlayerDynamicConfig() {
  }
  public static final int PROGRESS_FIELD_NUMBER = 1;
  private int progress_;
  /**
   * <pre>
   * 时间 毫秒数
   * </pre>
   *
   * <code>int32 progress = 1;</code>
   * @return The progress.
   */
  @java.lang.Override
  public int getProgress() {
    return progress_;
  }
  /**
   * <pre>
   * 时间 毫秒数
   * </pre>
   *
   * <code>int32 progress = 1;</code>
   * @param value The progress to set.
   */
  private void setProgress(int value) {
    
    progress_ = value;
  }
  /**
   * <pre>
   * 时间 毫秒数
   * </pre>
   *
   * <code>int32 progress = 1;</code>
   */
  private void clearProgress() {

    progress_ = 0;
  }

  public static final int PLAYER_DANMAKU_DOMAIN_FIELD_NUMBER = 14;
  private float playerDanmakuDomain_;
  /**
   * <pre>
   * 弹幕显示区域（0.25=1/4屏；0.5=半屏；0.75=3/4屏；1.0=满屏; 2.0=无限）
   * </pre>
   *
   * <code>float player_danmaku_domain = 14;</code>
   * @return The playerDanmakuDomain.
   */
  @java.lang.Override
  public float getPlayerDanmakuDomain() {
    return playerDanmakuDomain_;
  }
  /**
   * <pre>
   * 弹幕显示区域（0.25=1/4屏；0.5=半屏；0.75=3/4屏；1.0=满屏; 2.0=无限）
   * </pre>
   *
   * <code>float player_danmaku_domain = 14;</code>
   * @param value The playerDanmakuDomain to set.
   */
  private void setPlayerDanmakuDomain(float value) {
    
    playerDanmakuDomain_ = value;
  }
  /**
   * <pre>
   * 弹幕显示区域（0.25=1/4屏；0.5=半屏；0.75=3/4屏；1.0=满屏; 2.0=无限）
   * </pre>
   *
   * <code>float player_danmaku_domain = 14;</code>
   */
  private void clearPlayerDanmakuDomain() {

    playerDanmakuDomain_ = 0F;
  }

  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig, Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig)
      com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfigOrBuilder {
    // Construct using com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 时间 毫秒数
     * </pre>
     *
     * <code>int32 progress = 1;</code>
     * @return The progress.
     */
    @java.lang.Override
    public int getProgress() {
      return instance.getProgress();
    }
    /**
     * <pre>
     * 时间 毫秒数
     * </pre>
     *
     * <code>int32 progress = 1;</code>
     * @param value The progress to set.
     * @return This builder for chaining.
     */
    public Builder setProgress(int value) {
      copyOnWrite();
      instance.setProgress(value);
      return this;
    }
    /**
     * <pre>
     * 时间 毫秒数
     * </pre>
     *
     * <code>int32 progress = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgress() {
      copyOnWrite();
      instance.clearProgress();
      return this;
    }

    /**
     * <pre>
     * 弹幕显示区域（0.25=1/4屏；0.5=半屏；0.75=3/4屏；1.0=满屏; 2.0=无限）
     * </pre>
     *
     * <code>float player_danmaku_domain = 14;</code>
     * @return The playerDanmakuDomain.
     */
    @java.lang.Override
    public float getPlayerDanmakuDomain() {
      return instance.getPlayerDanmakuDomain();
    }
    /**
     * <pre>
     * 弹幕显示区域（0.25=1/4屏；0.5=半屏；0.75=3/4屏；1.0=满屏; 2.0=无限）
     * </pre>
     *
     * <code>float player_danmaku_domain = 14;</code>
     * @param value The playerDanmakuDomain to set.
     * @return This builder for chaining.
     */
    public Builder setPlayerDanmakuDomain(float value) {
      copyOnWrite();
      instance.setPlayerDanmakuDomain(value);
      return this;
    }
    /**
     * <pre>
     * 弹幕显示区域（0.25=1/4屏；0.5=半屏；0.75=3/4屏；1.0=满屏; 2.0=无限）
     * </pre>
     *
     * <code>float player_danmaku_domain = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayerDanmakuDomain() {
      copyOnWrite();
      instance.clearPlayerDanmakuDomain();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "progress_",
            "playerDanmakuDomain_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u000e\u0002\u0000\u0000\u0000\u0001\u0004\u000e\u0001" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig> parser = PARSER;
        if (parser == null) {
          synchronized (com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig)
  private static final com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig DEFAULT_INSTANCE;
  static {
    DanmuPlayerDynamicConfig defaultInstance = new DanmuPlayerDynamicConfig();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DanmuPlayerDynamicConfig.class, defaultInstance);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DanmuPlayerDynamicConfig> PARSER;

  public static com.google.protobuf.Parser<DanmuPlayerDynamicConfig> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

