// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

public interface DanmuPlayerDynamicConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.community.service.dm.v1.DanmuPlayerDynamicConfig)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * 时间 毫秒数
   * </pre>
   *
   * <code>int32 progress = 1;</code>
   * @return The progress.
   */
  int getProgress();

  /**
   * <pre>
   * 弹幕显示区域（0.25=1/4屏；0.5=半屏；0.75=3/4屏；1.0=满屏; 2.0=无限）
   * </pre>
   *
   * <code>float player_danmaku_domain = 14;</code>
   * @return The playerDanmakuDomain.
   */
  float getPlayerDanmakuDomain();
}
