// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

public interface DanmakuElemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.community.service.dm.v1.DanmakuElem)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * 弹幕id
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   * 弹幕位置
   * </pre>
   *
   * <code>int32 progress = 2;</code>
   * @return The progress.
   */
  int getProgress();

  /**
   * <pre>
   * 弹幕类型
   * </pre>
   *
   * <code>int32 mode = 3;</code>
   * @return The mode.
   */
  int getMode();

  /**
   * <pre>
   * 弹幕字体
   * </pre>
   *
   * <code>int32 fontsize = 4;</code>
   * @return The fontsize.
   */
  int getFontsize();

  /**
   * <pre>
   * 弹幕颜色
   * </pre>
   *
   * <code>uint32 color = 5;</code>
   * @return The color.
   */
  int getColor();

  /**
   * <pre>
   * 弹幕发送者md5哈希
   * </pre>
   *
   * <code>string mid_hash = 6;</code>
   * @return The midHash.
   */
  java.lang.String getMidHash();
  /**
   * <pre>
   * 弹幕发送者md5哈希
   * </pre>
   *
   * <code>string mid_hash = 6;</code>
   * @return The bytes for midHash.
   */
  com.google.protobuf.ByteString
      getMidHashBytes();

  /**
   * <pre>
   * 弹幕文本内容
   * </pre>
   *
   * <code>string content = 7;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * 弹幕文本内容
   * </pre>
   *
   * <code>string content = 7;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * 弹幕发送时间  时间戳
   * </pre>
   *
   * <code>int64 ctime = 8;</code>
   * @return The ctime.
   */
  long getCtime();

  /**
   * <pre>
   * 弹幕权重 越高显示优先级越高
   * </pre>
   *
   * <code>int32 weight = 9;</code>
   * @return The weight.
   */
  int getWeight();

  /**
   * <pre>
   * 弹幕动作
   * </pre>
   *
   * <code>string action = 10;</code>
   * @return The action.
   */
  java.lang.String getAction();
  /**
   * <pre>
   * 弹幕动作
   * </pre>
   *
   * <code>string action = 10;</code>
   * @return The bytes for action.
   */
  com.google.protobuf.ByteString
      getActionBytes();

  /**
   * <pre>
   * 弹幕池
   * </pre>
   *
   * <code>int32 pool = 11;</code>
   * @return The pool.
   */
  int getPool();

  /**
   * <pre>
   * 弹幕id_str
   * </pre>
   *
   * <code>string id_str = 12;</code>
   * @return The idStr.
   */
  java.lang.String getIdStr();
  /**
   * <pre>
   * 弹幕id_str
   * </pre>
   *
   * <code>string id_str = 12;</code>
   * @return The bytes for idStr.
   */
  com.google.protobuf.ByteString
      getIdStrBytes();

  /**
   * <pre>
   * 弹幕属性位 0保护弹幕 1直播弹幕 2高赞弹幕
   * </pre>
   *
   * <code>int32 attr = 13;</code>
   * @return The attr.
   */
  int getAttr();
}
