// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

public interface DmExpoReportReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.community.service.dm.v1.DmExpoReportReq)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * session id
   * </pre>
   *
   * <code>string session_id = 1;</code>
   * @return The sessionId.
   */
  java.lang.String getSessionId();
  /**
   * <pre>
   * session id
   * </pre>
   *
   * <code>string session_id = 1;</code>
   * @return The bytes for sessionId.
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * oid 视频id
   * </pre>
   *
   * <code>int64 oid = 2;</code>
   * @return The oid.
   */
  long getOid();

  /**
   * <pre>
   * gzip dmid, 逗号分隔
   * </pre>
   *
   * <code>bytes dmids = 3;</code>
   * @return The dmids.
   */
  com.google.protobuf.ByteString getDmids();

  /**
   * <pre>
   * spmid 页面id
   * </pre>
   *
   * <code>string spmid = 4;</code>
   * @return The spmid.
   */
  java.lang.String getSpmid();
  /**
   * <pre>
   * spmid 页面id
   * </pre>
   *
   * <code>string spmid = 4;</code>
   * @return The bytes for spmid.
   */
  com.google.protobuf.ByteString
      getSpmidBytes();
}
