// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

/**
 * <pre>
 * DmPlayerConfigReq.
 * </pre>
 *
 * Protobuf type {@code bilibili.community.service.dm.v1.DmPlayerConfigReq}
 */
public  final class DmPlayerConfigReq extends
    com.google.protobuf.GeneratedMessageLite<
        DmPlayerConfigReq, DmPlayerConfigReq.Builder> implements
    // @@protoc_insertion_point(message_implements:bilibili.community.service.dm.v1.DmPlayerConfigReq)
    DmPlayerConfigReqOrBuilder {
  private DmPlayerConfigReq() {
  }
  private int bitField0_;
  public static final int TS_FIELD_NUMBER = 1;
  private long ts_;
  /**
   * <code>int64 ts = 1;</code>
   * @return The ts.
   */
  @java.lang.Override
  public long getTs() {
    return ts_;
  }
  /**
   * <code>int64 ts = 1;</code>
   * @param value The ts to set.
   */
  private void setTs(long value) {
    
    ts_ = value;
  }
  /**
   * <code>int64 ts = 1;</code>
   */
  private void clearTs() {

    ts_ = 0L;
  }

  public static final int SWITCH_FIELD_NUMBER = 2;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
   */
  @java.lang.Override
  public boolean hasSwitch() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch getSwitch() {
    return switch_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch.getDefaultInstance() : switch_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSwitch(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch value) {
    value.getClass();  // minimal bytecode null check
    switch_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeSwitch(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch value) {
    value.getClass();  // minimal bytecode null check
    if (switch_ != null &&
        switch_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch.getDefaultInstance()) {
      switch_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch.newBuilder(switch_).mergeFrom(value).buildPartial();
    } else {
      switch_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
   */
  private void clearSwitch() {  switch_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int SWITCH_SAVE_FIELD_NUMBER = 3;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switchSave_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
   */
  @java.lang.Override
  public boolean hasSwitchSave() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave getSwitchSave() {
    return switchSave_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave.getDefaultInstance() : switchSave_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSwitchSave(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave value) {
    value.getClass();  // minimal bytecode null check
    switchSave_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeSwitchSave(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave value) {
    value.getClass();  // minimal bytecode null check
    if (switchSave_ != null &&
        switchSave_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave.getDefaultInstance()) {
      switchSave_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave.newBuilder(switchSave_).mergeFrom(value).buildPartial();
    } else {
      switchSave_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
   */
  private void clearSwitchSave() {  switchSave_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int USE_DEFAULT_CONFIG_FIELD_NUMBER = 4;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig useDefaultConfig_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
   */
  @java.lang.Override
  public boolean hasUseDefaultConfig() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig getUseDefaultConfig() {
    return useDefaultConfig_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig.getDefaultInstance() : useDefaultConfig_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setUseDefaultConfig(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig value) {
    value.getClass();  // minimal bytecode null check
    useDefaultConfig_ = value;
    bitField0_ |= 0x00000004;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeUseDefaultConfig(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig value) {
    value.getClass();  // minimal bytecode null check
    if (useDefaultConfig_ != null &&
        useDefaultConfig_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig.getDefaultInstance()) {
      useDefaultConfig_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig.newBuilder(useDefaultConfig_).mergeFrom(value).buildPartial();
    } else {
      useDefaultConfig_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
   */
  private void clearUseDefaultConfig() {  useDefaultConfig_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int AI_RECOMMENDED_SWITCH_FIELD_NUMBER = 5;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch aiRecommendedSwitch_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
   */
  @java.lang.Override
  public boolean hasAiRecommendedSwitch() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch getAiRecommendedSwitch() {
    return aiRecommendedSwitch_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch.getDefaultInstance() : aiRecommendedSwitch_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAiRecommendedSwitch(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch value) {
    value.getClass();  // minimal bytecode null check
    aiRecommendedSwitch_ = value;
    bitField0_ |= 0x00000008;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeAiRecommendedSwitch(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch value) {
    value.getClass();  // minimal bytecode null check
    if (aiRecommendedSwitch_ != null &&
        aiRecommendedSwitch_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch.getDefaultInstance()) {
      aiRecommendedSwitch_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch.newBuilder(aiRecommendedSwitch_).mergeFrom(value).buildPartial();
    } else {
      aiRecommendedSwitch_ = value;
    }
    bitField0_ |= 0x00000008;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
   */
  private void clearAiRecommendedSwitch() {  aiRecommendedSwitch_ = null;
    bitField0_ = (bitField0_ & ~0x00000008);
  }

  public static final int AI_RECOMMENDED_LEVEL_FIELD_NUMBER = 6;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel aiRecommendedLevel_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
   */
  @java.lang.Override
  public boolean hasAiRecommendedLevel() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel getAiRecommendedLevel() {
    return aiRecommendedLevel_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel.getDefaultInstance() : aiRecommendedLevel_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAiRecommendedLevel(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel value) {
    value.getClass();  // minimal bytecode null check
    aiRecommendedLevel_ = value;
    bitField0_ |= 0x00000010;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeAiRecommendedLevel(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel value) {
    value.getClass();  // minimal bytecode null check
    if (aiRecommendedLevel_ != null &&
        aiRecommendedLevel_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel.getDefaultInstance()) {
      aiRecommendedLevel_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel.newBuilder(aiRecommendedLevel_).mergeFrom(value).buildPartial();
    } else {
      aiRecommendedLevel_ = value;
    }
    bitField0_ |= 0x00000010;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
   */
  private void clearAiRecommendedLevel() {  aiRecommendedLevel_ = null;
    bitField0_ = (bitField0_ & ~0x00000010);
  }

  public static final int BLOCKTOP_FIELD_NUMBER = 7;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
   */
  @java.lang.Override
  public boolean hasBlocktop() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop getBlocktop() {
    return blocktop_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop.getDefaultInstance() : blocktop_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setBlocktop(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop value) {
    value.getClass();  // minimal bytecode null check
    blocktop_ = value;
    bitField0_ |= 0x00000020;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeBlocktop(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop value) {
    value.getClass();  // minimal bytecode null check
    if (blocktop_ != null &&
        blocktop_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop.getDefaultInstance()) {
      blocktop_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop.newBuilder(blocktop_).mergeFrom(value).buildPartial();
    } else {
      blocktop_ = value;
    }
    bitField0_ |= 0x00000020;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
   */
  private void clearBlocktop() {  blocktop_ = null;
    bitField0_ = (bitField0_ & ~0x00000020);
  }

  public static final int BLOCKSCROLL_FIELD_NUMBER = 8;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
   */
  @java.lang.Override
  public boolean hasBlockscroll() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll getBlockscroll() {
    return blockscroll_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll.getDefaultInstance() : blockscroll_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setBlockscroll(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll value) {
    value.getClass();  // minimal bytecode null check
    blockscroll_ = value;
    bitField0_ |= 0x00000040;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeBlockscroll(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll value) {
    value.getClass();  // minimal bytecode null check
    if (blockscroll_ != null &&
        blockscroll_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll.getDefaultInstance()) {
      blockscroll_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll.newBuilder(blockscroll_).mergeFrom(value).buildPartial();
    } else {
      blockscroll_ = value;
    }
    bitField0_ |= 0x00000040;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
   */
  private void clearBlockscroll() {  blockscroll_ = null;
    bitField0_ = (bitField0_ & ~0x00000040);
  }

  public static final int BLOCKBOTTOM_FIELD_NUMBER = 9;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
   */
  @java.lang.Override
  public boolean hasBlockbottom() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom getBlockbottom() {
    return blockbottom_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom.getDefaultInstance() : blockbottom_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setBlockbottom(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom value) {
    value.getClass();  // minimal bytecode null check
    blockbottom_ = value;
    bitField0_ |= 0x00000080;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeBlockbottom(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom value) {
    value.getClass();  // minimal bytecode null check
    if (blockbottom_ != null &&
        blockbottom_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom.getDefaultInstance()) {
      blockbottom_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom.newBuilder(blockbottom_).mergeFrom(value).buildPartial();
    } else {
      blockbottom_ = value;
    }
    bitField0_ |= 0x00000080;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
   */
  private void clearBlockbottom() {  blockbottom_ = null;
    bitField0_ = (bitField0_ & ~0x00000080);
  }

  public static final int BLOCKCOLORFUL_FIELD_NUMBER = 10;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
   */
  @java.lang.Override
  public boolean hasBlockcolorful() {
    return ((bitField0_ & 0x00000100) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful getBlockcolorful() {
    return blockcolorful_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful.getDefaultInstance() : blockcolorful_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setBlockcolorful(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful value) {
    value.getClass();  // minimal bytecode null check
    blockcolorful_ = value;
    bitField0_ |= 0x00000100;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeBlockcolorful(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful value) {
    value.getClass();  // minimal bytecode null check
    if (blockcolorful_ != null &&
        blockcolorful_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful.getDefaultInstance()) {
      blockcolorful_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful.newBuilder(blockcolorful_).mergeFrom(value).buildPartial();
    } else {
      blockcolorful_ = value;
    }
    bitField0_ |= 0x00000100;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
   */
  private void clearBlockcolorful() {  blockcolorful_ = null;
    bitField0_ = (bitField0_ & ~0x00000100);
  }

  public static final int BLOCKREPEAT_FIELD_NUMBER = 11;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
   */
  @java.lang.Override
  public boolean hasBlockrepeat() {
    return ((bitField0_ & 0x00000200) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat getBlockrepeat() {
    return blockrepeat_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat.getDefaultInstance() : blockrepeat_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setBlockrepeat(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat value) {
    value.getClass();  // minimal bytecode null check
    blockrepeat_ = value;
    bitField0_ |= 0x00000200;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeBlockrepeat(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat value) {
    value.getClass();  // minimal bytecode null check
    if (blockrepeat_ != null &&
        blockrepeat_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat.getDefaultInstance()) {
      blockrepeat_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat.newBuilder(blockrepeat_).mergeFrom(value).buildPartial();
    } else {
      blockrepeat_ = value;
    }
    bitField0_ |= 0x00000200;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
   */
  private void clearBlockrepeat() {  blockrepeat_ = null;
    bitField0_ = (bitField0_ & ~0x00000200);
  }

  public static final int BLOCKSPECIAL_FIELD_NUMBER = 12;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
   */
  @java.lang.Override
  public boolean hasBlockspecial() {
    return ((bitField0_ & 0x00000400) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial getBlockspecial() {
    return blockspecial_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial.getDefaultInstance() : blockspecial_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setBlockspecial(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial value) {
    value.getClass();  // minimal bytecode null check
    blockspecial_ = value;
    bitField0_ |= 0x00000400;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeBlockspecial(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial value) {
    value.getClass();  // minimal bytecode null check
    if (blockspecial_ != null &&
        blockspecial_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial.getDefaultInstance()) {
      blockspecial_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial.newBuilder(blockspecial_).mergeFrom(value).buildPartial();
    } else {
      blockspecial_ = value;
    }
    bitField0_ |= 0x00000400;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
   */
  private void clearBlockspecial() {  blockspecial_ = null;
    bitField0_ = (bitField0_ & ~0x00000400);
  }

  public static final int OPACITY_FIELD_NUMBER = 13;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
   */
  @java.lang.Override
  public boolean hasOpacity() {
    return ((bitField0_ & 0x00000800) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity getOpacity() {
    return opacity_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity.getDefaultInstance() : opacity_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setOpacity(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity value) {
    value.getClass();  // minimal bytecode null check
    opacity_ = value;
    bitField0_ |= 0x00000800;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeOpacity(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity value) {
    value.getClass();  // minimal bytecode null check
    if (opacity_ != null &&
        opacity_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity.getDefaultInstance()) {
      opacity_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity.newBuilder(opacity_).mergeFrom(value).buildPartial();
    } else {
      opacity_ = value;
    }
    bitField0_ |= 0x00000800;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
   */
  private void clearOpacity() {  opacity_ = null;
    bitField0_ = (bitField0_ & ~0x00000800);
  }

  public static final int SCALINGFACTOR_FIELD_NUMBER = 14;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
   */
  @java.lang.Override
  public boolean hasScalingfactor() {
    return ((bitField0_ & 0x00001000) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor getScalingfactor() {
    return scalingfactor_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor.getDefaultInstance() : scalingfactor_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setScalingfactor(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor value) {
    value.getClass();  // minimal bytecode null check
    scalingfactor_ = value;
    bitField0_ |= 0x00001000;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeScalingfactor(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor value) {
    value.getClass();  // minimal bytecode null check
    if (scalingfactor_ != null &&
        scalingfactor_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor.getDefaultInstance()) {
      scalingfactor_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor.newBuilder(scalingfactor_).mergeFrom(value).buildPartial();
    } else {
      scalingfactor_ = value;
    }
    bitField0_ |= 0x00001000;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
   */
  private void clearScalingfactor() {  scalingfactor_ = null;
    bitField0_ = (bitField0_ & ~0x00001000);
  }

  public static final int DOMAIN_FIELD_NUMBER = 15;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
   */
  @java.lang.Override
  public boolean hasDomain() {
    return ((bitField0_ & 0x00002000) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain getDomain() {
    return domain_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain.getDefaultInstance() : domain_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDomain(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain value) {
    value.getClass();  // minimal bytecode null check
    domain_ = value;
    bitField0_ |= 0x00002000;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeDomain(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain value) {
    value.getClass();  // minimal bytecode null check
    if (domain_ != null &&
        domain_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain.getDefaultInstance()) {
      domain_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain.newBuilder(domain_).mergeFrom(value).buildPartial();
    } else {
      domain_ = value;
    }
    bitField0_ |= 0x00002000;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
   */
  private void clearDomain() {  domain_ = null;
    bitField0_ = (bitField0_ & ~0x00002000);
  }

  public static final int SPEED_FIELD_NUMBER = 16;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
   */
  @java.lang.Override
  public boolean hasSpeed() {
    return ((bitField0_ & 0x00004000) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed getSpeed() {
    return speed_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed.getDefaultInstance() : speed_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSpeed(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed value) {
    value.getClass();  // minimal bytecode null check
    speed_ = value;
    bitField0_ |= 0x00004000;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeSpeed(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed value) {
    value.getClass();  // minimal bytecode null check
    if (speed_ != null &&
        speed_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed.getDefaultInstance()) {
      speed_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed.newBuilder(speed_).mergeFrom(value).buildPartial();
    } else {
      speed_ = value;
    }
    bitField0_ |= 0x00004000;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
   */
  private void clearSpeed() {  speed_ = null;
    bitField0_ = (bitField0_ & ~0x00004000);
  }

  public static final int ENABLEBLOCKLIST_FIELD_NUMBER = 17;
  private com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist_;
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
   */
  @java.lang.Override
  public boolean hasEnableblocklist() {
    return ((bitField0_ & 0x00008000) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist getEnableblocklist() {
    return enableblocklist_ == null ? com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist.getDefaultInstance() : enableblocklist_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setEnableblocklist(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist value) {
    value.getClass();  // minimal bytecode null check
    enableblocklist_ = value;
    bitField0_ |= 0x00008000;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeEnableblocklist(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist value) {
    value.getClass();  // minimal bytecode null check
    if (enableblocklist_ != null &&
        enableblocklist_ != com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist.getDefaultInstance()) {
      enableblocklist_ =
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist.newBuilder(enableblocklist_).mergeFrom(value).buildPartial();
    } else {
      enableblocklist_ = value;
    }
    bitField0_ |= 0x00008000;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
   */
  private void clearEnableblocklist() {  enableblocklist_ = null;
    bitField0_ = (bitField0_ & ~0x00008000);
  }

  public static final int INLINEPLAYERDANMAKUSWITCH_FIELD_NUMBER = 18;
  private com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch_;
  /**
   * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
   */
  @java.lang.Override
  public boolean hasInlinePlayerDanmakuSwitch() {
    return ((bitField0_ & 0x00010000) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch getInlinePlayerDanmakuSwitch() {
    return inlinePlayerDanmakuSwitch_ == null ? com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch.getDefaultInstance() : inlinePlayerDanmakuSwitch_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setInlinePlayerDanmakuSwitch(com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch value) {
    value.getClass();  // minimal bytecode null check
    inlinePlayerDanmakuSwitch_ = value;
    bitField0_ |= 0x00010000;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeInlinePlayerDanmakuSwitch(com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch value) {
    value.getClass();  // minimal bytecode null check
    if (inlinePlayerDanmakuSwitch_ != null &&
        inlinePlayerDanmakuSwitch_ != com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch.getDefaultInstance()) {
      inlinePlayerDanmakuSwitch_ =
        com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch.newBuilder(inlinePlayerDanmakuSwitch_).mergeFrom(value).buildPartial();
    } else {
      inlinePlayerDanmakuSwitch_ = value;
    }
    bitField0_ |= 0x00010000;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
   */
  private void clearInlinePlayerDanmakuSwitch() {  inlinePlayerDanmakuSwitch_ = null;
    bitField0_ = (bitField0_ & ~0x00010000);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * DmPlayerConfigReq.
   * </pre>
   *
   * Protobuf type {@code bilibili.community.service.dm.v1.DmPlayerConfigReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq, Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.community.service.dm.v1.DmPlayerConfigReq)
      com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReqOrBuilder {
    // Construct using com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 ts = 1;</code>
     * @return The ts.
     */
    @java.lang.Override
    public long getTs() {
      return instance.getTs();
    }
    /**
     * <code>int64 ts = 1;</code>
     * @param value The ts to set.
     * @return This builder for chaining.
     */
    public Builder setTs(long value) {
      copyOnWrite();
      instance.setTs(value);
      return this;
    }
    /**
     * <code>int64 ts = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTs() {
      copyOnWrite();
      instance.clearTs();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
     */
    @java.lang.Override
    public boolean hasSwitch() {
      return instance.hasSwitch();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch getSwitch() {
      return instance.getSwitch();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
     */
    public Builder setSwitch(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch value) {
      copyOnWrite();
      instance.setSwitch(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
     */
    public Builder setSwitch(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch.Builder builderForValue) {
      copyOnWrite();
      instance.setSwitch(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
     */
    public Builder mergeSwitch(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch value) {
      copyOnWrite();
      instance.mergeSwitch(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitch switch = 2;</code>
     */
    public Builder clearSwitch() {  copyOnWrite();
      instance.clearSwitch();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
     */
    @java.lang.Override
    public boolean hasSwitchSave() {
      return instance.hasSwitchSave();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave getSwitchSave() {
      return instance.getSwitchSave();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
     */
    public Builder setSwitchSave(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave value) {
      copyOnWrite();
      instance.setSwitchSave(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
     */
    public Builder setSwitchSave(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave.Builder builderForValue) {
      copyOnWrite();
      instance.setSwitchSave(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
     */
    public Builder mergeSwitchSave(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave value) {
      copyOnWrite();
      instance.mergeSwitchSave(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSwitchSave switch_save = 3;</code>
     */
    public Builder clearSwitchSave() {  copyOnWrite();
      instance.clearSwitchSave();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
     */
    @java.lang.Override
    public boolean hasUseDefaultConfig() {
      return instance.hasUseDefaultConfig();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig getUseDefaultConfig() {
      return instance.getUseDefaultConfig();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
     */
    public Builder setUseDefaultConfig(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig value) {
      copyOnWrite();
      instance.setUseDefaultConfig(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
     */
    public Builder setUseDefaultConfig(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig.Builder builderForValue) {
      copyOnWrite();
      instance.setUseDefaultConfig(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
     */
    public Builder mergeUseDefaultConfig(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig value) {
      copyOnWrite();
      instance.mergeUseDefaultConfig(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuUseDefaultConfig use_default_config = 4;</code>
     */
    public Builder clearUseDefaultConfig() {  copyOnWrite();
      instance.clearUseDefaultConfig();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
     */
    @java.lang.Override
    public boolean hasAiRecommendedSwitch() {
      return instance.hasAiRecommendedSwitch();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch getAiRecommendedSwitch() {
      return instance.getAiRecommendedSwitch();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
     */
    public Builder setAiRecommendedSwitch(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch value) {
      copyOnWrite();
      instance.setAiRecommendedSwitch(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
     */
    public Builder setAiRecommendedSwitch(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch.Builder builderForValue) {
      copyOnWrite();
      instance.setAiRecommendedSwitch(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
     */
    public Builder mergeAiRecommendedSwitch(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch value) {
      copyOnWrite();
      instance.mergeAiRecommendedSwitch(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedSwitch ai_recommended_switch = 5;</code>
     */
    public Builder clearAiRecommendedSwitch() {  copyOnWrite();
      instance.clearAiRecommendedSwitch();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
     */
    @java.lang.Override
    public boolean hasAiRecommendedLevel() {
      return instance.hasAiRecommendedLevel();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel getAiRecommendedLevel() {
      return instance.getAiRecommendedLevel();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
     */
    public Builder setAiRecommendedLevel(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel value) {
      copyOnWrite();
      instance.setAiRecommendedLevel(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
     */
    public Builder setAiRecommendedLevel(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel.Builder builderForValue) {
      copyOnWrite();
      instance.setAiRecommendedLevel(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
     */
    public Builder mergeAiRecommendedLevel(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel value) {
      copyOnWrite();
      instance.mergeAiRecommendedLevel(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuAiRecommendedLevel ai_recommended_level = 6;</code>
     */
    public Builder clearAiRecommendedLevel() {  copyOnWrite();
      instance.clearAiRecommendedLevel();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
     */
    @java.lang.Override
    public boolean hasBlocktop() {
      return instance.hasBlocktop();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop getBlocktop() {
      return instance.getBlocktop();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
     */
    public Builder setBlocktop(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop value) {
      copyOnWrite();
      instance.setBlocktop(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
     */
    public Builder setBlocktop(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop.Builder builderForValue) {
      copyOnWrite();
      instance.setBlocktop(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
     */
    public Builder mergeBlocktop(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop value) {
      copyOnWrite();
      instance.mergeBlocktop(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlocktop blocktop = 7;</code>
     */
    public Builder clearBlocktop() {  copyOnWrite();
      instance.clearBlocktop();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
     */
    @java.lang.Override
    public boolean hasBlockscroll() {
      return instance.hasBlockscroll();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll getBlockscroll() {
      return instance.getBlockscroll();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
     */
    public Builder setBlockscroll(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll value) {
      copyOnWrite();
      instance.setBlockscroll(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
     */
    public Builder setBlockscroll(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll.Builder builderForValue) {
      copyOnWrite();
      instance.setBlockscroll(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
     */
    public Builder mergeBlockscroll(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll value) {
      copyOnWrite();
      instance.mergeBlockscroll(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockscroll blockscroll = 8;</code>
     */
    public Builder clearBlockscroll() {  copyOnWrite();
      instance.clearBlockscroll();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
     */
    @java.lang.Override
    public boolean hasBlockbottom() {
      return instance.hasBlockbottom();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom getBlockbottom() {
      return instance.getBlockbottom();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
     */
    public Builder setBlockbottom(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom value) {
      copyOnWrite();
      instance.setBlockbottom(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
     */
    public Builder setBlockbottom(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom.Builder builderForValue) {
      copyOnWrite();
      instance.setBlockbottom(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
     */
    public Builder mergeBlockbottom(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom value) {
      copyOnWrite();
      instance.mergeBlockbottom(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockbottom blockbottom = 9;</code>
     */
    public Builder clearBlockbottom() {  copyOnWrite();
      instance.clearBlockbottom();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
     */
    @java.lang.Override
    public boolean hasBlockcolorful() {
      return instance.hasBlockcolorful();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful getBlockcolorful() {
      return instance.getBlockcolorful();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
     */
    public Builder setBlockcolorful(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful value) {
      copyOnWrite();
      instance.setBlockcolorful(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
     */
    public Builder setBlockcolorful(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful.Builder builderForValue) {
      copyOnWrite();
      instance.setBlockcolorful(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
     */
    public Builder mergeBlockcolorful(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful value) {
      copyOnWrite();
      instance.mergeBlockcolorful(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockcolorful blockcolorful = 10;</code>
     */
    public Builder clearBlockcolorful() {  copyOnWrite();
      instance.clearBlockcolorful();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
     */
    @java.lang.Override
    public boolean hasBlockrepeat() {
      return instance.hasBlockrepeat();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat getBlockrepeat() {
      return instance.getBlockrepeat();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
     */
    public Builder setBlockrepeat(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat value) {
      copyOnWrite();
      instance.setBlockrepeat(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
     */
    public Builder setBlockrepeat(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat.Builder builderForValue) {
      copyOnWrite();
      instance.setBlockrepeat(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
     */
    public Builder mergeBlockrepeat(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat value) {
      copyOnWrite();
      instance.mergeBlockrepeat(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockrepeat blockrepeat = 11;</code>
     */
    public Builder clearBlockrepeat() {  copyOnWrite();
      instance.clearBlockrepeat();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
     */
    @java.lang.Override
    public boolean hasBlockspecial() {
      return instance.hasBlockspecial();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial getBlockspecial() {
      return instance.getBlockspecial();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
     */
    public Builder setBlockspecial(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial value) {
      copyOnWrite();
      instance.setBlockspecial(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
     */
    public Builder setBlockspecial(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial.Builder builderForValue) {
      copyOnWrite();
      instance.setBlockspecial(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
     */
    public Builder mergeBlockspecial(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial value) {
      copyOnWrite();
      instance.mergeBlockspecial(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuBlockspecial blockspecial = 12;</code>
     */
    public Builder clearBlockspecial() {  copyOnWrite();
      instance.clearBlockspecial();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
     */
    @java.lang.Override
    public boolean hasOpacity() {
      return instance.hasOpacity();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity getOpacity() {
      return instance.getOpacity();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
     */
    public Builder setOpacity(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity value) {
      copyOnWrite();
      instance.setOpacity(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
     */
    public Builder setOpacity(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity.Builder builderForValue) {
      copyOnWrite();
      instance.setOpacity(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
     */
    public Builder mergeOpacity(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuOpacity value) {
      copyOnWrite();
      instance.mergeOpacity(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuOpacity opacity = 13;</code>
     */
    public Builder clearOpacity() {  copyOnWrite();
      instance.clearOpacity();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
     */
    @java.lang.Override
    public boolean hasScalingfactor() {
      return instance.hasScalingfactor();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor getScalingfactor() {
      return instance.getScalingfactor();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
     */
    public Builder setScalingfactor(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor value) {
      copyOnWrite();
      instance.setScalingfactor(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
     */
    public Builder setScalingfactor(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor.Builder builderForValue) {
      copyOnWrite();
      instance.setScalingfactor(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
     */
    public Builder mergeScalingfactor(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor value) {
      copyOnWrite();
      instance.mergeScalingfactor(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuScalingfactor scalingfactor = 14;</code>
     */
    public Builder clearScalingfactor() {  copyOnWrite();
      instance.clearScalingfactor();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
     */
    @java.lang.Override
    public boolean hasDomain() {
      return instance.hasDomain();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain getDomain() {
      return instance.getDomain();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
     */
    public Builder setDomain(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain value) {
      copyOnWrite();
      instance.setDomain(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
     */
    public Builder setDomain(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain.Builder builderForValue) {
      copyOnWrite();
      instance.setDomain(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
     */
    public Builder mergeDomain(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuDomain value) {
      copyOnWrite();
      instance.mergeDomain(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuDomain domain = 15;</code>
     */
    public Builder clearDomain() {  copyOnWrite();
      instance.clearDomain();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
     */
    @java.lang.Override
    public boolean hasSpeed() {
      return instance.hasSpeed();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed getSpeed() {
      return instance.getSpeed();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
     */
    public Builder setSpeed(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed value) {
      copyOnWrite();
      instance.setSpeed(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
     */
    public Builder setSpeed(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed.Builder builderForValue) {
      copyOnWrite();
      instance.setSpeed(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
     */
    public Builder mergeSpeed(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSpeed value) {
      copyOnWrite();
      instance.mergeSpeed(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuSpeed speed = 16;</code>
     */
    public Builder clearSpeed() {  copyOnWrite();
      instance.clearSpeed();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
     */
    @java.lang.Override
    public boolean hasEnableblocklist() {
      return instance.hasEnableblocklist();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist getEnableblocklist() {
      return instance.getEnableblocklist();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
     */
    public Builder setEnableblocklist(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist value) {
      copyOnWrite();
      instance.setEnableblocklist(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
     */
    public Builder setEnableblocklist(
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist.Builder builderForValue) {
      copyOnWrite();
      instance.setEnableblocklist(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
     */
    public Builder mergeEnableblocklist(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist value) {
      copyOnWrite();
      instance.mergeEnableblocklist(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.PlayerDanmakuEnableblocklist enableblocklist = 17;</code>
     */
    public Builder clearEnableblocklist() {  copyOnWrite();
      instance.clearEnableblocklist();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
     */
    @java.lang.Override
    public boolean hasInlinePlayerDanmakuSwitch() {
      return instance.hasInlinePlayerDanmakuSwitch();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch getInlinePlayerDanmakuSwitch() {
      return instance.getInlinePlayerDanmakuSwitch();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
     */
    public Builder setInlinePlayerDanmakuSwitch(com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch value) {
      copyOnWrite();
      instance.setInlinePlayerDanmakuSwitch(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
     */
    public Builder setInlinePlayerDanmakuSwitch(
        com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch.Builder builderForValue) {
      copyOnWrite();
      instance.setInlinePlayerDanmakuSwitch(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
     */
    public Builder mergeInlinePlayerDanmakuSwitch(com.bapis.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch value) {
      copyOnWrite();
      instance.mergeInlinePlayerDanmakuSwitch(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.InlinePlayerDanmakuSwitch inlinePlayerDanmakuSwitch = 18;</code>
     */
    public Builder clearInlinePlayerDanmakuSwitch() {  copyOnWrite();
      instance.clearInlinePlayerDanmakuSwitch();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.community.service.dm.v1.DmPlayerConfigReq)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "ts_",
            "switch_",
            "switchSave_",
            "useDefaultConfig_",
            "aiRecommendedSwitch_",
            "aiRecommendedLevel_",
            "blocktop_",
            "blockscroll_",
            "blockbottom_",
            "blockcolorful_",
            "blockrepeat_",
            "blockspecial_",
            "opacity_",
            "scalingfactor_",
            "domain_",
            "speed_",
            "enableblocklist_",
            "inlinePlayerDanmakuSwitch_",
          };
          java.lang.String info =
              "\u0000\u0012\u0000\u0001\u0001\u0012\u0012\u0000\u0000\u0000\u0001\u0002\u0002\u1009" +
              "\u0000\u0003\u1009\u0001\u0004\u1009\u0002\u0005\u1009\u0003\u0006\u1009\u0004\u0007" +
              "\u1009\u0005\b\u1009\u0006\t\u1009\u0007\n\u1009\b\u000b\u1009\t\f\u1009\n\r\u1009" +
              "\u000b\u000e\u1009\f\u000f\u1009\r\u0010\u1009\u000e\u0011\u1009\u000f\u0012\u1009" +
              "\u0010";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq> parser = PARSER;
        if (parser == null) {
          synchronized (com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bilibili.community.service.dm.v1.DmPlayerConfigReq)
  private static final com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq DEFAULT_INSTANCE;
  static {
    DmPlayerConfigReq defaultInstance = new DmPlayerConfigReq();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DmPlayerConfigReq.class, defaultInstance);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DmPlayerConfigReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DmPlayerConfigReq> PARSER;

  public static com.google.protobuf.Parser<DmPlayerConfigReq> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

