// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

/**
 * <pre>
 * DmViewReply 弹幕view返回
 * </pre>
 *
 * Protobuf type {@code bilibili.community.service.dm.v1.DmWebViewReply}
 */
public  final class DmWebViewReply extends
    com.google.protobuf.GeneratedMessageLite<
        DmWebViewReply, DmWebViewReply.Builder> implements
    // @@protoc_insertion_point(message_implements:bilibili.community.service.dm.v1.DmWebViewReply)
    DmWebViewReplyOrBuilder {
  private DmWebViewReply() {
    text_ = "";
    textSide_ = "";
    specialDms_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    commandDms_ = emptyProtobufList();
    reportFilterContent_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    expressions_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int STATE_FIELD_NUMBER = 1;
  private int state_;
  /**
   * <pre>
   * 弹幕区是否关闭
   * </pre>
   *
   * <code>int32 state = 1;</code>
   * @return The state.
   */
  @java.lang.Override
  public int getState() {
    return state_;
  }
  /**
   * <pre>
   * 弹幕区是否关闭
   * </pre>
   *
   * <code>int32 state = 1;</code>
   * @param value The state to set.
   */
  private void setState(int value) {
    
    state_ = value;
  }
  /**
   * <pre>
   * 弹幕区是否关闭
   * </pre>
   *
   * <code>int32 state = 1;</code>
   */
  private void clearState() {

    state_ = 0;
  }

  public static final int TEXT_FIELD_NUMBER = 2;
  private java.lang.String text_;
  /**
   * <pre>
   * </pre>
   *
   * <code>string text = 2;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    return text_;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string text = 2;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(text_);
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string text = 2;</code>
   * @param value The text to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setText(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    text_ = value;
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string text = 2;</code>
   */
  private void clearText() {

    text_ = getDefaultInstance().getText();
  }
  /**
   * <pre>
   * </pre>
   *
   * <code>string text = 2;</code>
   * @param value The bytes for text to set.
   */
  private void setTextBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    text_ = value.toStringUtf8();

  }

  public static final int TEXT_SIDE_FIELD_NUMBER = 3;
  private java.lang.String textSide_;
  /**
   * <code>string text_side = 3;</code>
   * @return The textSide.
   */
  @java.lang.Override
  public java.lang.String getTextSide() {
    return textSide_;
  }
  /**
   * <code>string text_side = 3;</code>
   * @return The bytes for textSide.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextSideBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(textSide_);
  }
  /**
   * <code>string text_side = 3;</code>
   * @param value The textSide to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setTextSide(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    textSide_ = value;
  }
  /**
   * <code>string text_side = 3;</code>
   */
  private void clearTextSide() {

    textSide_ = getDefaultInstance().getTextSide();
  }
  /**
   * <code>string text_side = 3;</code>
   * @param value The bytes for textSide to set.
   */
  private void setTextSideBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    textSide_ = value.toStringUtf8();

  }

  public static final int DM_SGE_FIELD_NUMBER = 4;
  private com.bapis.bilibili.community.service.dm.v1.DmSegConfig dmSge_;
  /**
   * <pre>
   * 分段弹幕配置
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
   */
  @java.lang.Override
  public boolean hasDmSge() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 分段弹幕配置
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.DmSegConfig getDmSge() {
    return dmSge_ == null ? com.bapis.bilibili.community.service.dm.v1.DmSegConfig.getDefaultInstance() : dmSge_;
  }
  /**
   * <pre>
   * 分段弹幕配置
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setDmSge(com.bapis.bilibili.community.service.dm.v1.DmSegConfig value) {
    value.getClass();  // minimal bytecode null check
    dmSge_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <pre>
   * 分段弹幕配置
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeDmSge(com.bapis.bilibili.community.service.dm.v1.DmSegConfig value) {
    value.getClass();  // minimal bytecode null check
    if (dmSge_ != null &&
        dmSge_ != com.bapis.bilibili.community.service.dm.v1.DmSegConfig.getDefaultInstance()) {
      dmSge_ =
        com.bapis.bilibili.community.service.dm.v1.DmSegConfig.newBuilder(dmSge_).mergeFrom(value).buildPartial();
    } else {
      dmSge_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * 分段弹幕配置
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
   */
  private void clearDmSge() {  dmSge_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int FLAG_FIELD_NUMBER = 5;
  private com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig flag_;
  /**
   * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
   */
  @java.lang.Override
  public boolean hasFlag() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig getFlag() {
    return flag_ == null ? com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig.getDefaultInstance() : flag_;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setFlag(com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig value) {
    value.getClass();  // minimal bytecode null check
    flag_ = value;
    bitField0_ |= 0x00000002;
    }
  /**
   * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeFlag(com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig value) {
    value.getClass();  // minimal bytecode null check
    if (flag_ != null &&
        flag_ != com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig.getDefaultInstance()) {
      flag_ =
        com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig.newBuilder(flag_).mergeFrom(value).buildPartial();
    } else {
      flag_ = value;
    }
    bitField0_ |= 0x00000002;
  }
  /**
   * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
   */
  private void clearFlag() {  flag_ = null;
    bitField0_ = (bitField0_ & ~0x00000002);
  }

  public static final int SPECIAL_DMS_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> specialDms_;
  /**
   * <pre>
   * 高级弹幕链接地址 （上传到bfs）
   * </pre>
   *
   * <code>repeated string special_dms = 6;</code>
   * @return A list containing the specialDms.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getSpecialDmsList() {
    return specialDms_;
  }
  /**
   * <pre>
   * 高级弹幕链接地址 （上传到bfs）
   * </pre>
   *
   * <code>repeated string special_dms = 6;</code>
   * @return The count of specialDms.
   */
  @java.lang.Override
  public int getSpecialDmsCount() {
    return specialDms_.size();
  }
  /**
   * <pre>
   * 高级弹幕链接地址 （上传到bfs）
   * </pre>
   *
   * <code>repeated string special_dms = 6;</code>
   * @param index The index of the element to return.
   * @return The specialDms at the given index.
   */
  @java.lang.Override
  public java.lang.String getSpecialDms(int index) {
    return specialDms_.get(index);
  }
  /**
   * <pre>
   * 高级弹幕链接地址 （上传到bfs）
   * </pre>
   *
   * <code>repeated string special_dms = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the specialDms at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSpecialDmsBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        specialDms_.get(index));
  }
  private void ensureSpecialDmsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        specialDms_;  if (!tmp.isModifiable()) {
      specialDms_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * 高级弹幕链接地址 （上传到bfs）
   * </pre>
   *
   * <code>repeated string special_dms = 6;</code>
   * @param index The index to set the value at.
   * @param value The specialDms to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSpecialDms(
      int index, java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureSpecialDmsIsMutable();
    specialDms_.set(index, value);
  }
  /**
   * <pre>
   * 高级弹幕链接地址 （上传到bfs）
   * </pre>
   *
   * <code>repeated string special_dms = 6;</code>
   * @param value The specialDms to add.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addSpecialDms(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureSpecialDmsIsMutable();
    specialDms_.add(value);
  }
  /**
   * <pre>
   * 高级弹幕链接地址 （上传到bfs）
   * </pre>
   *
   * <code>repeated string special_dms = 6;</code>
   * @param values The specialDms to add.
   */
  private void addAllSpecialDms(
      java.lang.Iterable<java.lang.String> values) {
    ensureSpecialDmsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, specialDms_);
  }
  /**
   * <pre>
   * 高级弹幕链接地址 （上传到bfs）
   * </pre>
   *
   * <code>repeated string special_dms = 6;</code>
   */
  private void clearSpecialDms() {
    specialDms_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * 高级弹幕链接地址 （上传到bfs）
   * </pre>
   *
   * <code>repeated string special_dms = 6;</code>
   * @param value The bytes of the specialDms to add.
   */
  private void addSpecialDmsBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureSpecialDmsIsMutable();
    specialDms_.add(value.toStringUtf8());
  }

  public static final int CHECK_BOX_FIELD_NUMBER = 7;
  private boolean checkBox_;
  /**
   * <pre>
   * check box 是否展示
   * </pre>
   *
   * <code>bool check_box = 7;</code>
   * @return The checkBox.
   */
  @java.lang.Override
  public boolean getCheckBox() {
    return checkBox_;
  }
  /**
   * <pre>
   * check box 是否展示
   * </pre>
   *
   * <code>bool check_box = 7;</code>
   * @param value The checkBox to set.
   */
  private void setCheckBox(boolean value) {
    
    checkBox_ = value;
  }
  /**
   * <pre>
   * check box 是否展示
   * </pre>
   *
   * <code>bool check_box = 7;</code>
   */
  private void clearCheckBox() {

    checkBox_ = false;
  }

  public static final int COUNT_FIELD_NUMBER = 8;
  private long count_;
  /**
   * <pre>
   * 弹幕数
   * </pre>
   *
   * <code>int64 count = 8;</code>
   * @return The count.
   */
  @java.lang.Override
  public long getCount() {
    return count_;
  }
  /**
   * <pre>
   * 弹幕数
   * </pre>
   *
   * <code>int64 count = 8;</code>
   * @param value The count to set.
   */
  private void setCount(long value) {
    
    count_ = value;
  }
  /**
   * <pre>
   * 弹幕数
   * </pre>
   *
   * <code>int64 count = 8;</code>
   */
  private void clearCount() {

    count_ = 0L;
  }

  public static final int COMMANDDMS_FIELD_NUMBER = 9;
  private com.google.protobuf.Internal.ProtobufList<com.bapis.bilibili.community.service.dm.v1.CommandDm> commandDms_;
  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  @java.lang.Override
  public java.util.List<com.bapis.bilibili.community.service.dm.v1.CommandDm> getCommandDmsList() {
    return commandDms_;
  }
  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  public java.util.List<? extends com.bapis.bilibili.community.service.dm.v1.CommandDmOrBuilder> 
      getCommandDmsOrBuilderList() {
    return commandDms_;
  }
  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  @java.lang.Override
  public int getCommandDmsCount() {
    return commandDms_.size();
  }
  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.CommandDm getCommandDms(int index) {
    return commandDms_.get(index);
  }
  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  public com.bapis.bilibili.community.service.dm.v1.CommandDmOrBuilder getCommandDmsOrBuilder(
      int index) {
    return commandDms_.get(index);
  }
  private void ensureCommandDmsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.bapis.bilibili.community.service.dm.v1.CommandDm> tmp = commandDms_;
    if (!tmp.isModifiable()) {
      commandDms_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setCommandDms(
      int index, com.bapis.bilibili.community.service.dm.v1.CommandDm value) {
    value.getClass();  // minimal bytecode null check
    ensureCommandDmsIsMutable();
    commandDms_.set(index, value);
  }
  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addCommandDms(com.bapis.bilibili.community.service.dm.v1.CommandDm value) {
    value.getClass();  // minimal bytecode null check
    ensureCommandDmsIsMutable();
    commandDms_.add(value);
  }
  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addCommandDms(
      int index, com.bapis.bilibili.community.service.dm.v1.CommandDm value) {
    value.getClass();  // minimal bytecode null check
    ensureCommandDmsIsMutable();
    commandDms_.add(index, value);
  }
  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  private void addAllCommandDms(
      java.lang.Iterable<? extends com.bapis.bilibili.community.service.dm.v1.CommandDm> values) {
    ensureCommandDmsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, commandDms_);
  }
  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  private void clearCommandDms() {
    commandDms_ = emptyProtobufList();
  }
  /**
   * <pre>
   * CommandDm
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
   */
  private void removeCommandDms(int index) {
    ensureCommandDmsIsMutable();
    commandDms_.remove(index);
  }

  public static final int PLAYER_CONFIG_FIELD_NUMBER = 10;
  private com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig playerConfig_;
  /**
   * <pre>
   * 用户弹幕配置
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
   */
  @java.lang.Override
  public boolean hasPlayerConfig() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * 用户弹幕配置
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig getPlayerConfig() {
    return playerConfig_ == null ? com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig.getDefaultInstance() : playerConfig_;
  }
  /**
   * <pre>
   * 用户弹幕配置
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setPlayerConfig(com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig value) {
    value.getClass();  // minimal bytecode null check
    playerConfig_ = value;
    bitField0_ |= 0x00000004;
    }
  /**
   * <pre>
   * 用户弹幕配置
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergePlayerConfig(com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig value) {
    value.getClass();  // minimal bytecode null check
    if (playerConfig_ != null &&
        playerConfig_ != com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig.getDefaultInstance()) {
      playerConfig_ =
        com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig.newBuilder(playerConfig_).mergeFrom(value).buildPartial();
    } else {
      playerConfig_ = value;
    }
    bitField0_ |= 0x00000004;
  }
  /**
   * <pre>
   * 用户弹幕配置
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
   */
  private void clearPlayerConfig() {  playerConfig_ = null;
    bitField0_ = (bitField0_ & ~0x00000004);
  }

  public static final int REPORT_FILTER_CONTENT_FIELD_NUMBER = 11;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> reportFilterContent_;
  /**
   * <pre>
   * 用户举报弹幕，cid维度屏蔽
   * </pre>
   *
   * <code>repeated string report_filter_content = 11;</code>
   * @return A list containing the reportFilterContent.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getReportFilterContentList() {
    return reportFilterContent_;
  }
  /**
   * <pre>
   * 用户举报弹幕，cid维度屏蔽
   * </pre>
   *
   * <code>repeated string report_filter_content = 11;</code>
   * @return The count of reportFilterContent.
   */
  @java.lang.Override
  public int getReportFilterContentCount() {
    return reportFilterContent_.size();
  }
  /**
   * <pre>
   * 用户举报弹幕，cid维度屏蔽
   * </pre>
   *
   * <code>repeated string report_filter_content = 11;</code>
   * @param index The index of the element to return.
   * @return The reportFilterContent at the given index.
   */
  @java.lang.Override
  public java.lang.String getReportFilterContent(int index) {
    return reportFilterContent_.get(index);
  }
  /**
   * <pre>
   * 用户举报弹幕，cid维度屏蔽
   * </pre>
   *
   * <code>repeated string report_filter_content = 11;</code>
   * @param index The index of the value to return.
   * @return The bytes of the reportFilterContent at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReportFilterContentBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        reportFilterContent_.get(index));
  }
  private void ensureReportFilterContentIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        reportFilterContent_;  if (!tmp.isModifiable()) {
      reportFilterContent_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * 用户举报弹幕，cid维度屏蔽
   * </pre>
   *
   * <code>repeated string report_filter_content = 11;</code>
   * @param index The index to set the value at.
   * @param value The reportFilterContent to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setReportFilterContent(
      int index, java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureReportFilterContentIsMutable();
    reportFilterContent_.set(index, value);
  }
  /**
   * <pre>
   * 用户举报弹幕，cid维度屏蔽
   * </pre>
   *
   * <code>repeated string report_filter_content = 11;</code>
   * @param value The reportFilterContent to add.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addReportFilterContent(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureReportFilterContentIsMutable();
    reportFilterContent_.add(value);
  }
  /**
   * <pre>
   * 用户举报弹幕，cid维度屏蔽
   * </pre>
   *
   * <code>repeated string report_filter_content = 11;</code>
   * @param values The reportFilterContent to add.
   */
  private void addAllReportFilterContent(
      java.lang.Iterable<java.lang.String> values) {
    ensureReportFilterContentIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, reportFilterContent_);
  }
  /**
   * <pre>
   * 用户举报弹幕，cid维度屏蔽
   * </pre>
   *
   * <code>repeated string report_filter_content = 11;</code>
   */
  private void clearReportFilterContent() {
    reportFilterContent_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * 用户举报弹幕，cid维度屏蔽
   * </pre>
   *
   * <code>repeated string report_filter_content = 11;</code>
   * @param value The bytes of the reportFilterContent to add.
   */
  private void addReportFilterContentBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureReportFilterContentIsMutable();
    reportFilterContent_.add(value.toStringUtf8());
  }

  public static final int EXPRESSIONS_FIELD_NUMBER = 12;
  private com.google.protobuf.Internal.ProtobufList<com.bapis.bilibili.community.service.dm.v1.Expressions> expressions_;
  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  @java.lang.Override
  public java.util.List<com.bapis.bilibili.community.service.dm.v1.Expressions> getExpressionsList() {
    return expressions_;
  }
  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  public java.util.List<? extends com.bapis.bilibili.community.service.dm.v1.ExpressionsOrBuilder> 
      getExpressionsOrBuilderList() {
    return expressions_;
  }
  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  @java.lang.Override
  public int getExpressionsCount() {
    return expressions_.size();
  }
  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.Expressions getExpressions(int index) {
    return expressions_.get(index);
  }
  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  public com.bapis.bilibili.community.service.dm.v1.ExpressionsOrBuilder getExpressionsOrBuilder(
      int index) {
    return expressions_.get(index);
  }
  private void ensureExpressionsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.bapis.bilibili.community.service.dm.v1.Expressions> tmp = expressions_;
    if (!tmp.isModifiable()) {
      expressions_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setExpressions(
      int index, com.bapis.bilibili.community.service.dm.v1.Expressions value) {
    value.getClass();  // minimal bytecode null check
    ensureExpressionsIsMutable();
    expressions_.set(index, value);
  }
  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addExpressions(com.bapis.bilibili.community.service.dm.v1.Expressions value) {
    value.getClass();  // minimal bytecode null check
    ensureExpressionsIsMutable();
    expressions_.add(value);
  }
  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addExpressions(
      int index, com.bapis.bilibili.community.service.dm.v1.Expressions value) {
    value.getClass();  // minimal bytecode null check
    ensureExpressionsIsMutable();
    expressions_.add(index, value);
  }
  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  private void addAllExpressions(
      java.lang.Iterable<? extends com.bapis.bilibili.community.service.dm.v1.Expressions> values) {
    ensureExpressionsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, expressions_);
  }
  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  private void clearExpressions() {
    expressions_ = emptyProtobufList();
  }
  /**
   * <pre>
   * 图片弹幕
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
   */
  private void removeExpressions(int index) {
    ensureExpressionsIsMutable();
    expressions_.remove(index);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.community.service.dm.v1.DmWebViewReply prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * DmViewReply 弹幕view返回
   * </pre>
   *
   * Protobuf type {@code bilibili.community.service.dm.v1.DmWebViewReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.bapis.bilibili.community.service.dm.v1.DmWebViewReply, Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.community.service.dm.v1.DmWebViewReply)
      com.bapis.bilibili.community.service.dm.v1.DmWebViewReplyOrBuilder {
    // Construct using com.bapis.bilibili.community.service.dm.v1.DmWebViewReply.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 弹幕区是否关闭
     * </pre>
     *
     * <code>int32 state = 1;</code>
     * @return The state.
     */
    @java.lang.Override
    public int getState() {
      return instance.getState();
    }
    /**
     * <pre>
     * 弹幕区是否关闭
     * </pre>
     *
     * <code>int32 state = 1;</code>
     * @param value The state to set.
     * @return This builder for chaining.
     */
    public Builder setState(int value) {
      copyOnWrite();
      instance.setState(value);
      return this;
    }
    /**
     * <pre>
     * 弹幕区是否关闭
     * </pre>
     *
     * <code>int32 state = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearState() {
      copyOnWrite();
      instance.clearState();
      return this;
    }

    /**
     * <pre>
     * </pre>
     *
     * <code>string text = 2;</code>
     * @return The text.
     */
    @java.lang.Override
    public java.lang.String getText() {
      return instance.getText();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string text = 2;</code>
     * @return The bytes for text.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextBytes() {
      return instance.getTextBytes();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string text = 2;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      copyOnWrite();
      instance.setText(value);
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string text = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      copyOnWrite();
      instance.clearText();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>string text = 2;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTextBytes(value);
      return this;
    }

    /**
     * <code>string text_side = 3;</code>
     * @return The textSide.
     */
    @java.lang.Override
    public java.lang.String getTextSide() {
      return instance.getTextSide();
    }
    /**
     * <code>string text_side = 3;</code>
     * @return The bytes for textSide.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTextSideBytes() {
      return instance.getTextSideBytes();
    }
    /**
     * <code>string text_side = 3;</code>
     * @param value The textSide to set.
     * @return This builder for chaining.
     */
    public Builder setTextSide(
        java.lang.String value) {
      copyOnWrite();
      instance.setTextSide(value);
      return this;
    }
    /**
     * <code>string text_side = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTextSide() {
      copyOnWrite();
      instance.clearTextSide();
      return this;
    }
    /**
     * <code>string text_side = 3;</code>
     * @param value The bytes for textSide to set.
     * @return This builder for chaining.
     */
    public Builder setTextSideBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTextSideBytes(value);
      return this;
    }

    /**
     * <pre>
     * 分段弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
     */
    @java.lang.Override
    public boolean hasDmSge() {
      return instance.hasDmSge();
    }
    /**
     * <pre>
     * 分段弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.DmSegConfig getDmSge() {
      return instance.getDmSge();
    }
    /**
     * <pre>
     * 分段弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
     */
    public Builder setDmSge(com.bapis.bilibili.community.service.dm.v1.DmSegConfig value) {
      copyOnWrite();
      instance.setDmSge(value);
      return this;
      }
    /**
     * <pre>
     * 分段弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
     */
    public Builder setDmSge(
        com.bapis.bilibili.community.service.dm.v1.DmSegConfig.Builder builderForValue) {
      copyOnWrite();
      instance.setDmSge(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 分段弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
     */
    public Builder mergeDmSge(com.bapis.bilibili.community.service.dm.v1.DmSegConfig value) {
      copyOnWrite();
      instance.mergeDmSge(value);
      return this;
    }
    /**
     * <pre>
     * 分段弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DmSegConfig dm_sge = 4;</code>
     */
    public Builder clearDmSge() {  copyOnWrite();
      instance.clearDmSge();
      return this;
    }

    /**
     * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
     */
    @java.lang.Override
    public boolean hasFlag() {
      return instance.hasFlag();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig getFlag() {
      return instance.getFlag();
    }
    /**
     * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
     */
    public Builder setFlag(com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig value) {
      copyOnWrite();
      instance.setFlag(value);
      return this;
      }
    /**
     * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
     */
    public Builder setFlag(
        com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig.Builder builderForValue) {
      copyOnWrite();
      instance.setFlag(builderForValue.build());
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
     */
    public Builder mergeFlag(com.bapis.bilibili.community.service.dm.v1.DanmakuFlagConfig value) {
      copyOnWrite();
      instance.mergeFlag(value);
      return this;
    }
    /**
     * <code>.bilibili.community.service.dm.v1.DanmakuFlagConfig flag = 5;</code>
     */
    public Builder clearFlag() {  copyOnWrite();
      instance.clearFlag();
      return this;
    }

    /**
     * <pre>
     * 高级弹幕链接地址 （上传到bfs）
     * </pre>
     *
     * <code>repeated string special_dms = 6;</code>
     * @return A list containing the specialDms.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getSpecialDmsList() {
      return java.util.Collections.unmodifiableList(
          instance.getSpecialDmsList());
    }
    /**
     * <pre>
     * 高级弹幕链接地址 （上传到bfs）
     * </pre>
     *
     * <code>repeated string special_dms = 6;</code>
     * @return The count of specialDms.
     */
    @java.lang.Override
    public int getSpecialDmsCount() {
      return instance.getSpecialDmsCount();
    }
    /**
     * <pre>
     * 高级弹幕链接地址 （上传到bfs）
     * </pre>
     *
     * <code>repeated string special_dms = 6;</code>
     * @param index The index of the element to return.
     * @return The specialDms at the given index.
     */
    @java.lang.Override
    public java.lang.String getSpecialDms(int index) {
      return instance.getSpecialDms(index);
    }
    /**
     * <pre>
     * 高级弹幕链接地址 （上传到bfs）
     * </pre>
     *
     * <code>repeated string special_dms = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the specialDms at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSpecialDmsBytes(int index) {
      return instance.getSpecialDmsBytes(index);
    }
    /**
     * <pre>
     * 高级弹幕链接地址 （上传到bfs）
     * </pre>
     *
     * <code>repeated string special_dms = 6;</code>
     * @param index The index to set the value at.
     * @param value The specialDms to set.
     * @return This builder for chaining.
     */
    public Builder setSpecialDms(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setSpecialDms(index, value);
      return this;
    }
    /**
     * <pre>
     * 高级弹幕链接地址 （上传到bfs）
     * </pre>
     *
     * <code>repeated string special_dms = 6;</code>
     * @param value The specialDms to add.
     * @return This builder for chaining.
     */
    public Builder addSpecialDms(
        java.lang.String value) {
      copyOnWrite();
      instance.addSpecialDms(value);
      return this;
    }
    /**
     * <pre>
     * 高级弹幕链接地址 （上传到bfs）
     * </pre>
     *
     * <code>repeated string special_dms = 6;</code>
     * @param values The specialDms to add.
     * @return This builder for chaining.
     */
    public Builder addAllSpecialDms(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllSpecialDms(values);
      return this;
    }
    /**
     * <pre>
     * 高级弹幕链接地址 （上传到bfs）
     * </pre>
     *
     * <code>repeated string special_dms = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSpecialDms() {
      copyOnWrite();
      instance.clearSpecialDms();
      return this;
    }
    /**
     * <pre>
     * 高级弹幕链接地址 （上传到bfs）
     * </pre>
     *
     * <code>repeated string special_dms = 6;</code>
     * @param value The bytes of the specialDms to add.
     * @return This builder for chaining.
     */
    public Builder addSpecialDmsBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addSpecialDmsBytes(value);
      return this;
    }

    /**
     * <pre>
     * check box 是否展示
     * </pre>
     *
     * <code>bool check_box = 7;</code>
     * @return The checkBox.
     */
    @java.lang.Override
    public boolean getCheckBox() {
      return instance.getCheckBox();
    }
    /**
     * <pre>
     * check box 是否展示
     * </pre>
     *
     * <code>bool check_box = 7;</code>
     * @param value The checkBox to set.
     * @return This builder for chaining.
     */
    public Builder setCheckBox(boolean value) {
      copyOnWrite();
      instance.setCheckBox(value);
      return this;
    }
    /**
     * <pre>
     * check box 是否展示
     * </pre>
     *
     * <code>bool check_box = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCheckBox() {
      copyOnWrite();
      instance.clearCheckBox();
      return this;
    }

    /**
     * <pre>
     * 弹幕数
     * </pre>
     *
     * <code>int64 count = 8;</code>
     * @return The count.
     */
    @java.lang.Override
    public long getCount() {
      return instance.getCount();
    }
    /**
     * <pre>
     * 弹幕数
     * </pre>
     *
     * <code>int64 count = 8;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(long value) {
      copyOnWrite();
      instance.setCount(value);
      return this;
    }
    /**
     * <pre>
     * 弹幕数
     * </pre>
     *
     * <code>int64 count = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      copyOnWrite();
      instance.clearCount();
      return this;
    }

    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    @java.lang.Override
    public java.util.List<com.bapis.bilibili.community.service.dm.v1.CommandDm> getCommandDmsList() {
      return java.util.Collections.unmodifiableList(
          instance.getCommandDmsList());
    }
    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    @java.lang.Override
    public int getCommandDmsCount() {
      return instance.getCommandDmsCount();
    }/**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.CommandDm getCommandDms(int index) {
      return instance.getCommandDms(index);
    }
    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    public Builder setCommandDms(
        int index, com.bapis.bilibili.community.service.dm.v1.CommandDm value) {
      copyOnWrite();
      instance.setCommandDms(index, value);
      return this;
    }
    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    public Builder setCommandDms(
        int index, com.bapis.bilibili.community.service.dm.v1.CommandDm.Builder builderForValue) {
      copyOnWrite();
      instance.setCommandDms(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    public Builder addCommandDms(com.bapis.bilibili.community.service.dm.v1.CommandDm value) {
      copyOnWrite();
      instance.addCommandDms(value);
      return this;
    }
    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    public Builder addCommandDms(
        int index, com.bapis.bilibili.community.service.dm.v1.CommandDm value) {
      copyOnWrite();
      instance.addCommandDms(index, value);
      return this;
    }
    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    public Builder addCommandDms(
        com.bapis.bilibili.community.service.dm.v1.CommandDm.Builder builderForValue) {
      copyOnWrite();
      instance.addCommandDms(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    public Builder addCommandDms(
        int index, com.bapis.bilibili.community.service.dm.v1.CommandDm.Builder builderForValue) {
      copyOnWrite();
      instance.addCommandDms(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    public Builder addAllCommandDms(
        java.lang.Iterable<? extends com.bapis.bilibili.community.service.dm.v1.CommandDm> values) {
      copyOnWrite();
      instance.addAllCommandDms(values);
      return this;
    }
    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    public Builder clearCommandDms() {
      copyOnWrite();
      instance.clearCommandDms();
      return this;
    }
    /**
     * <pre>
     * CommandDm
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.CommandDm commandDms = 9;</code>
     */
    public Builder removeCommandDms(int index) {
      copyOnWrite();
      instance.removeCommandDms(index);
      return this;
    }

    /**
     * <pre>
     * 用户弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
     */
    @java.lang.Override
    public boolean hasPlayerConfig() {
      return instance.hasPlayerConfig();
    }
    /**
     * <pre>
     * 用户弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig getPlayerConfig() {
      return instance.getPlayerConfig();
    }
    /**
     * <pre>
     * 用户弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
     */
    public Builder setPlayerConfig(com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig value) {
      copyOnWrite();
      instance.setPlayerConfig(value);
      return this;
      }
    /**
     * <pre>
     * 用户弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
     */
    public Builder setPlayerConfig(
        com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig.Builder builderForValue) {
      copyOnWrite();
      instance.setPlayerConfig(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 用户弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
     */
    public Builder mergePlayerConfig(com.bapis.bilibili.community.service.dm.v1.DanmuWebPlayerConfig value) {
      copyOnWrite();
      instance.mergePlayerConfig(value);
      return this;
    }
    /**
     * <pre>
     * 用户弹幕配置
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.DanmuWebPlayerConfig player_config = 10;</code>
     */
    public Builder clearPlayerConfig() {  copyOnWrite();
      instance.clearPlayerConfig();
      return this;
    }

    /**
     * <pre>
     * 用户举报弹幕，cid维度屏蔽
     * </pre>
     *
     * <code>repeated string report_filter_content = 11;</code>
     * @return A list containing the reportFilterContent.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getReportFilterContentList() {
      return java.util.Collections.unmodifiableList(
          instance.getReportFilterContentList());
    }
    /**
     * <pre>
     * 用户举报弹幕，cid维度屏蔽
     * </pre>
     *
     * <code>repeated string report_filter_content = 11;</code>
     * @return The count of reportFilterContent.
     */
    @java.lang.Override
    public int getReportFilterContentCount() {
      return instance.getReportFilterContentCount();
    }
    /**
     * <pre>
     * 用户举报弹幕，cid维度屏蔽
     * </pre>
     *
     * <code>repeated string report_filter_content = 11;</code>
     * @param index The index of the element to return.
     * @return The reportFilterContent at the given index.
     */
    @java.lang.Override
    public java.lang.String getReportFilterContent(int index) {
      return instance.getReportFilterContent(index);
    }
    /**
     * <pre>
     * 用户举报弹幕，cid维度屏蔽
     * </pre>
     *
     * <code>repeated string report_filter_content = 11;</code>
     * @param index The index of the value to return.
     * @return The bytes of the reportFilterContent at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReportFilterContentBytes(int index) {
      return instance.getReportFilterContentBytes(index);
    }
    /**
     * <pre>
     * 用户举报弹幕，cid维度屏蔽
     * </pre>
     *
     * <code>repeated string report_filter_content = 11;</code>
     * @param index The index to set the value at.
     * @param value The reportFilterContent to set.
     * @return This builder for chaining.
     */
    public Builder setReportFilterContent(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setReportFilterContent(index, value);
      return this;
    }
    /**
     * <pre>
     * 用户举报弹幕，cid维度屏蔽
     * </pre>
     *
     * <code>repeated string report_filter_content = 11;</code>
     * @param value The reportFilterContent to add.
     * @return This builder for chaining.
     */
    public Builder addReportFilterContent(
        java.lang.String value) {
      copyOnWrite();
      instance.addReportFilterContent(value);
      return this;
    }
    /**
     * <pre>
     * 用户举报弹幕，cid维度屏蔽
     * </pre>
     *
     * <code>repeated string report_filter_content = 11;</code>
     * @param values The reportFilterContent to add.
     * @return This builder for chaining.
     */
    public Builder addAllReportFilterContent(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllReportFilterContent(values);
      return this;
    }
    /**
     * <pre>
     * 用户举报弹幕，cid维度屏蔽
     * </pre>
     *
     * <code>repeated string report_filter_content = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearReportFilterContent() {
      copyOnWrite();
      instance.clearReportFilterContent();
      return this;
    }
    /**
     * <pre>
     * 用户举报弹幕，cid维度屏蔽
     * </pre>
     *
     * <code>repeated string report_filter_content = 11;</code>
     * @param value The bytes of the reportFilterContent to add.
     * @return This builder for chaining.
     */
    public Builder addReportFilterContentBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addReportFilterContentBytes(value);
      return this;
    }

    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    @java.lang.Override
    public java.util.List<com.bapis.bilibili.community.service.dm.v1.Expressions> getExpressionsList() {
      return java.util.Collections.unmodifiableList(
          instance.getExpressionsList());
    }
    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    @java.lang.Override
    public int getExpressionsCount() {
      return instance.getExpressionsCount();
    }/**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.Expressions getExpressions(int index) {
      return instance.getExpressions(index);
    }
    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    public Builder setExpressions(
        int index, com.bapis.bilibili.community.service.dm.v1.Expressions value) {
      copyOnWrite();
      instance.setExpressions(index, value);
      return this;
    }
    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    public Builder setExpressions(
        int index, com.bapis.bilibili.community.service.dm.v1.Expressions.Builder builderForValue) {
      copyOnWrite();
      instance.setExpressions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    public Builder addExpressions(com.bapis.bilibili.community.service.dm.v1.Expressions value) {
      copyOnWrite();
      instance.addExpressions(value);
      return this;
    }
    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    public Builder addExpressions(
        int index, com.bapis.bilibili.community.service.dm.v1.Expressions value) {
      copyOnWrite();
      instance.addExpressions(index, value);
      return this;
    }
    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    public Builder addExpressions(
        com.bapis.bilibili.community.service.dm.v1.Expressions.Builder builderForValue) {
      copyOnWrite();
      instance.addExpressions(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    public Builder addExpressions(
        int index, com.bapis.bilibili.community.service.dm.v1.Expressions.Builder builderForValue) {
      copyOnWrite();
      instance.addExpressions(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    public Builder addAllExpressions(
        java.lang.Iterable<? extends com.bapis.bilibili.community.service.dm.v1.Expressions> values) {
      copyOnWrite();
      instance.addAllExpressions(values);
      return this;
    }
    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    public Builder clearExpressions() {
      copyOnWrite();
      instance.clearExpressions();
      return this;
    }
    /**
     * <pre>
     * 图片弹幕
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.Expressions expressions = 12;</code>
     */
    public Builder removeExpressions(int index) {
      copyOnWrite();
      instance.removeExpressions(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.community.service.dm.v1.DmWebViewReply)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.bapis.bilibili.community.service.dm.v1.DmWebViewReply();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "state_",
            "text_",
            "textSide_",
            "dmSge_",
            "flag_",
            "specialDms_",
            "checkBox_",
            "count_",
            "commandDms_",
            com.bapis.bilibili.community.service.dm.v1.CommandDm.class,
            "playerConfig_",
            "reportFilterContent_",
            "expressions_",
            com.bapis.bilibili.community.service.dm.v1.Expressions.class,
          };
          java.lang.String info =
              "\u0000\f\u0000\u0001\u0001\f\f\u0000\u0004\u0000\u0001\u0004\u0002\u0208\u0003\u0208" +
              "\u0004\u1009\u0000\u0005\u1009\u0001\u0006\u021a\u0007\u0007\b\u0002\t\u001b\n\u1009" +
              "\u0002\u000b\u021a\f\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.bapis.bilibili.community.service.dm.v1.DmWebViewReply> parser = PARSER;
        if (parser == null) {
          synchronized (com.bapis.bilibili.community.service.dm.v1.DmWebViewReply.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.bapis.bilibili.community.service.dm.v1.DmWebViewReply>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bilibili.community.service.dm.v1.DmWebViewReply)
  private static final com.bapis.bilibili.community.service.dm.v1.DmWebViewReply DEFAULT_INSTANCE;
  static {
    DmWebViewReply defaultInstance = new DmWebViewReply();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      DmWebViewReply.class, defaultInstance);
  }

  public static com.bapis.bilibili.community.service.dm.v1.DmWebViewReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<DmWebViewReply> PARSER;

  public static com.google.protobuf.Parser<DmWebViewReply> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

