// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

/**
 * Protobuf type {@code bilibili.community.service.dm.v1.Expression}
 */
public  final class Expression extends
    com.google.protobuf.GeneratedMessageLite<
        Expression, Expression.Builder> implements
    // @@protoc_insertion_point(message_implements:bilibili.community.service.dm.v1.Expression)
    ExpressionOrBuilder {
  private Expression() {
    keyword_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    url_ = "";
    period_ = emptyProtobufList();
  }
  public static final int KEYWORD_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> keyword_;
  /**
   * <code>repeated string keyword = 1;</code>
   * @return A list containing the keyword.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getKeywordList() {
    return keyword_;
  }
  /**
   * <code>repeated string keyword = 1;</code>
   * @return The count of keyword.
   */
  @java.lang.Override
  public int getKeywordCount() {
    return keyword_.size();
  }
  /**
   * <code>repeated string keyword = 1;</code>
   * @param index The index of the element to return.
   * @return The keyword at the given index.
   */
  @java.lang.Override
  public java.lang.String getKeyword(int index) {
    return keyword_.get(index);
  }
  /**
   * <code>repeated string keyword = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the keyword at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeywordBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        keyword_.get(index));
  }
  private void ensureKeywordIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        keyword_;  if (!tmp.isModifiable()) {
      keyword_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <code>repeated string keyword = 1;</code>
   * @param index The index to set the value at.
   * @param value The keyword to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setKeyword(
      int index, java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureKeywordIsMutable();
    keyword_.set(index, value);
  }
  /**
   * <code>repeated string keyword = 1;</code>
   * @param value The keyword to add.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addKeyword(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check
    ensureKeywordIsMutable();
    keyword_.add(value);
  }
  /**
   * <code>repeated string keyword = 1;</code>
   * @param values The keyword to add.
   */
  private void addAllKeyword(
      java.lang.Iterable<java.lang.String> values) {
    ensureKeywordIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, keyword_);
  }
  /**
   * <code>repeated string keyword = 1;</code>
   */
  private void clearKeyword() {
    keyword_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <code>repeated string keyword = 1;</code>
   * @param value The bytes of the keyword to add.
   */
  private void addKeywordBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureKeywordIsMutable();
    keyword_.add(value.toStringUtf8());
  }

  public static final int URL_FIELD_NUMBER = 2;
  private java.lang.String url_;
  /**
   * <code>string url = 2;</code>
   * @return The url.
   */
  @java.lang.Override
  public java.lang.String getUrl() {
    return url_;
  }
  /**
   * <code>string url = 2;</code>
   * @return The bytes for url.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(url_);
  }
  /**
   * <code>string url = 2;</code>
   * @param value The url to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setUrl(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    url_ = value;
  }
  /**
   * <code>string url = 2;</code>
   */
  private void clearUrl() {

    url_ = getDefaultInstance().getUrl();
  }
  /**
   * <code>string url = 2;</code>
   * @param value The bytes for url to set.
   */
  private void setUrlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    url_ = value.toStringUtf8();

  }

  public static final int PERIOD_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<com.bapis.bilibili.community.service.dm.v1.Period> period_;
  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.bapis.bilibili.community.service.dm.v1.Period> getPeriodList() {
    return period_;
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  public java.util.List<? extends com.bapis.bilibili.community.service.dm.v1.PeriodOrBuilder> 
      getPeriodOrBuilderList() {
    return period_;
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  @java.lang.Override
  public int getPeriodCount() {
    return period_.size();
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.Period getPeriod(int index) {
    return period_.get(index);
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  public com.bapis.bilibili.community.service.dm.v1.PeriodOrBuilder getPeriodOrBuilder(
      int index) {
    return period_.get(index);
  }
  private void ensurePeriodIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.bapis.bilibili.community.service.dm.v1.Period> tmp = period_;
    if (!tmp.isModifiable()) {
      period_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setPeriod(
      int index, com.bapis.bilibili.community.service.dm.v1.Period value) {
    value.getClass();  // minimal bytecode null check
    ensurePeriodIsMutable();
    period_.set(index, value);
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addPeriod(com.bapis.bilibili.community.service.dm.v1.Period value) {
    value.getClass();  // minimal bytecode null check
    ensurePeriodIsMutable();
    period_.add(value);
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addPeriod(
      int index, com.bapis.bilibili.community.service.dm.v1.Period value) {
    value.getClass();  // minimal bytecode null check
    ensurePeriodIsMutable();
    period_.add(index, value);
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  private void addAllPeriod(
      java.lang.Iterable<? extends com.bapis.bilibili.community.service.dm.v1.Period> values) {
    ensurePeriodIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, period_);
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  private void clearPeriod() {
    period_ = emptyProtobufList();
  }
  /**
   * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
   */
  private void removePeriod(int index) {
    ensurePeriodIsMutable();
    period_.remove(index);
  }

  public static com.bapis.bilibili.community.service.dm.v1.Expression parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.Expression parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.Expression parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.Expression parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.Expression parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.Expression parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.Expression parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.Expression parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.bapis.bilibili.community.service.dm.v1.Expression parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.bapis.bilibili.community.service.dm.v1.Expression parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.Expression parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.Expression parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.community.service.dm.v1.Expression prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code bilibili.community.service.dm.v1.Expression}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.bapis.bilibili.community.service.dm.v1.Expression, Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.community.service.dm.v1.Expression)
      com.bapis.bilibili.community.service.dm.v1.ExpressionOrBuilder {
    // Construct using com.bapis.bilibili.community.service.dm.v1.Expression.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>repeated string keyword = 1;</code>
     * @return A list containing the keyword.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getKeywordList() {
      return java.util.Collections.unmodifiableList(
          instance.getKeywordList());
    }
    /**
     * <code>repeated string keyword = 1;</code>
     * @return The count of keyword.
     */
    @java.lang.Override
    public int getKeywordCount() {
      return instance.getKeywordCount();
    }
    /**
     * <code>repeated string keyword = 1;</code>
     * @param index The index of the element to return.
     * @return The keyword at the given index.
     */
    @java.lang.Override
    public java.lang.String getKeyword(int index) {
      return instance.getKeyword(index);
    }
    /**
     * <code>repeated string keyword = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the keyword at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeywordBytes(int index) {
      return instance.getKeywordBytes(index);
    }
    /**
     * <code>repeated string keyword = 1;</code>
     * @param index The index to set the value at.
     * @param value The keyword to set.
     * @return This builder for chaining.
     */
    public Builder setKeyword(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setKeyword(index, value);
      return this;
    }
    /**
     * <code>repeated string keyword = 1;</code>
     * @param value The keyword to add.
     * @return This builder for chaining.
     */
    public Builder addKeyword(
        java.lang.String value) {
      copyOnWrite();
      instance.addKeyword(value);
      return this;
    }
    /**
     * <code>repeated string keyword = 1;</code>
     * @param values The keyword to add.
     * @return This builder for chaining.
     */
    public Builder addAllKeyword(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllKeyword(values);
      return this;
    }
    /**
     * <code>repeated string keyword = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyword() {
      copyOnWrite();
      instance.clearKeyword();
      return this;
    }
    /**
     * <code>repeated string keyword = 1;</code>
     * @param value The bytes of the keyword to add.
     * @return This builder for chaining.
     */
    public Builder addKeywordBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addKeywordBytes(value);
      return this;
    }

    /**
     * <code>string url = 2;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      return instance.getUrl();
    }
    /**
     * <code>string url = 2;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      return instance.getUrlBytes();
    }
    /**
     * <code>string url = 2;</code>
     * @param value The url to set.
     * @return This builder for chaining.
     */
    public Builder setUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setUrl(value);
      return this;
    }
    /**
     * <code>string url = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUrl() {
      copyOnWrite();
      instance.clearUrl();
      return this;
    }
    /**
     * <code>string url = 2;</code>
     * @param value The bytes for url to set.
     * @return This builder for chaining.
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setUrlBytes(value);
      return this;
    }

    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.bapis.bilibili.community.service.dm.v1.Period> getPeriodList() {
      return java.util.Collections.unmodifiableList(
          instance.getPeriodList());
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    @java.lang.Override
    public int getPeriodCount() {
      return instance.getPeriodCount();
    }/**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.Period getPeriod(int index) {
      return instance.getPeriod(index);
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    public Builder setPeriod(
        int index, com.bapis.bilibili.community.service.dm.v1.Period value) {
      copyOnWrite();
      instance.setPeriod(index, value);
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    public Builder setPeriod(
        int index, com.bapis.bilibili.community.service.dm.v1.Period.Builder builderForValue) {
      copyOnWrite();
      instance.setPeriod(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    public Builder addPeriod(com.bapis.bilibili.community.service.dm.v1.Period value) {
      copyOnWrite();
      instance.addPeriod(value);
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    public Builder addPeriod(
        int index, com.bapis.bilibili.community.service.dm.v1.Period value) {
      copyOnWrite();
      instance.addPeriod(index, value);
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    public Builder addPeriod(
        com.bapis.bilibili.community.service.dm.v1.Period.Builder builderForValue) {
      copyOnWrite();
      instance.addPeriod(builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    public Builder addPeriod(
        int index, com.bapis.bilibili.community.service.dm.v1.Period.Builder builderForValue) {
      copyOnWrite();
      instance.addPeriod(index,
          builderForValue.build());
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    public Builder addAllPeriod(
        java.lang.Iterable<? extends com.bapis.bilibili.community.service.dm.v1.Period> values) {
      copyOnWrite();
      instance.addAllPeriod(values);
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    public Builder clearPeriod() {
      copyOnWrite();
      instance.clearPeriod();
      return this;
    }
    /**
     * <code>repeated .bilibili.community.service.dm.v1.Period period = 3;</code>
     */
    public Builder removePeriod(int index) {
      copyOnWrite();
      instance.removePeriod(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.community.service.dm.v1.Expression)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.bapis.bilibili.community.service.dm.v1.Expression();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "keyword_",
            "url_",
            "period_",
            com.bapis.bilibili.community.service.dm.v1.Period.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0002\u0000\u0001\u021a\u0002\u0208" +
              "\u0003\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.bapis.bilibili.community.service.dm.v1.Expression> parser = PARSER;
        if (parser == null) {
          synchronized (com.bapis.bilibili.community.service.dm.v1.Expression.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.bapis.bilibili.community.service.dm.v1.Expression>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bilibili.community.service.dm.v1.Expression)
  private static final com.bapis.bilibili.community.service.dm.v1.Expression DEFAULT_INSTANCE;
  static {
    Expression defaultInstance = new Expression();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Expression.class, defaultInstance);
  }

  public static com.bapis.bilibili.community.service.dm.v1.Expression getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Expression> PARSER;

  public static com.google.protobuf.Parser<Expression> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

