// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

/**
 * Protobuf type {@code bilibili.community.service.dm.v1.PlayerDanmakuSwitch}
 */
public  final class PlayerDanmakuSwitch extends
    com.google.protobuf.GeneratedMessageLite<
        PlayerDanmakuSwitch, PlayerDanmakuSwitch.Builder> implements
    // @@protoc_insertion_point(message_implements:bilibili.community.service.dm.v1.PlayerDanmakuSwitch)
    PlayerDanmakuSwitchOrBuilder {
  private PlayerDanmakuSwitch() {
  }
  public static final int VALUE_FIELD_NUMBER = 1;
  private boolean value_;
  /**
   * <code>bool value = 1;</code>
   * @return The value.
   */
  @java.lang.Override
  public boolean getValue() {
    return value_;
  }
  /**
   * <code>bool value = 1;</code>
   * @param value The value to set.
   */
  private void setValue(boolean value) {
    
    value_ = value;
  }
  /**
   * <code>bool value = 1;</code>
   */
  private void clearValue() {

    value_ = false;
  }

  public static final int CANIGNORE_FIELD_NUMBER = 2;
  private boolean canIgnore_;
  /**
   * <code>bool canIgnore = 2;</code>
   * @return The canIgnore.
   */
  @java.lang.Override
  public boolean getCanIgnore() {
    return canIgnore_;
  }
  /**
   * <code>bool canIgnore = 2;</code>
   * @param value The canIgnore to set.
   */
  private void setCanIgnore(boolean value) {
    
    canIgnore_ = value;
  }
  /**
   * <code>bool canIgnore = 2;</code>
   */
  private void clearCanIgnore() {

    canIgnore_ = false;
  }

  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code bilibili.community.service.dm.v1.PlayerDanmakuSwitch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch, Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.community.service.dm.v1.PlayerDanmakuSwitch)
      com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitchOrBuilder {
    // Construct using com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>bool value = 1;</code>
     * @return The value.
     */
    @java.lang.Override
    public boolean getValue() {
      return instance.getValue();
    }
    /**
     * <code>bool value = 1;</code>
     * @param value The value to set.
     * @return This builder for chaining.
     */
    public Builder setValue(boolean value) {
      copyOnWrite();
      instance.setValue(value);
      return this;
    }
    /**
     * <code>bool value = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }

    /**
     * <code>bool canIgnore = 2;</code>
     * @return The canIgnore.
     */
    @java.lang.Override
    public boolean getCanIgnore() {
      return instance.getCanIgnore();
    }
    /**
     * <code>bool canIgnore = 2;</code>
     * @param value The canIgnore to set.
     * @return This builder for chaining.
     */
    public Builder setCanIgnore(boolean value) {
      copyOnWrite();
      instance.setCanIgnore(value);
      return this;
    }
    /**
     * <code>bool canIgnore = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCanIgnore() {
      copyOnWrite();
      instance.clearCanIgnore();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.community.service.dm.v1.PlayerDanmakuSwitch)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "value_",
            "canIgnore_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0007\u0002\u0007" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch> parser = PARSER;
        if (parser == null) {
          synchronized (com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bilibili.community.service.dm.v1.PlayerDanmakuSwitch)
  private static final com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch DEFAULT_INSTANCE;
  static {
    PlayerDanmakuSwitch defaultInstance = new PlayerDanmakuSwitch();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PlayerDanmakuSwitch.class, defaultInstance);
  }

  public static com.bapis.bilibili.community.service.dm.v1.PlayerDanmakuSwitch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PlayerDanmakuSwitch> PARSER;

  public static com.google.protobuf.Parser<PlayerDanmakuSwitch> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

