// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

/**
 * <pre>
 * SubtitleItem 单个字幕信息
 * </pre>
 *
 * Protobuf type {@code bilibili.community.service.dm.v1.SubtitleItem}
 */
public  final class SubtitleItem extends
    com.google.protobuf.GeneratedMessageLite<
        SubtitleItem, SubtitleItem.Builder> implements
    // @@protoc_insertion_point(message_implements:bilibili.community.service.dm.v1.SubtitleItem)
    SubtitleItemOrBuilder {
  private SubtitleItem() {
    idStr_ = "";
    lan_ = "";
    lanDoc_ = "";
    subtitleUrl_ = "";
  }
  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <pre>
   * 字幕id
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }
  /**
   * <pre>
   * 字幕id
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @param value The id to set.
   */
  private void setId(long value) {
    
    id_ = value;
  }
  /**
   * <pre>
   * 字幕id
   * </pre>
   *
   * <code>int64 id = 1;</code>
   */
  private void clearId() {

    id_ = 0L;
  }

  public static final int ID_STR_FIELD_NUMBER = 2;
  private java.lang.String idStr_;
  /**
   * <pre>
   * 字幕id string
   * </pre>
   *
   * <code>string id_str = 2;</code>
   * @return The idStr.
   */
  @java.lang.Override
  public java.lang.String getIdStr() {
    return idStr_;
  }
  /**
   * <pre>
   * 字幕id string
   * </pre>
   *
   * <code>string id_str = 2;</code>
   * @return The bytes for idStr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdStrBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(idStr_);
  }
  /**
   * <pre>
   * 字幕id string
   * </pre>
   *
   * <code>string id_str = 2;</code>
   * @param value The idStr to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setIdStr(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    idStr_ = value;
  }
  /**
   * <pre>
   * 字幕id string
   * </pre>
   *
   * <code>string id_str = 2;</code>
   */
  private void clearIdStr() {

    idStr_ = getDefaultInstance().getIdStr();
  }
  /**
   * <pre>
   * 字幕id string
   * </pre>
   *
   * <code>string id_str = 2;</code>
   * @param value The bytes for idStr to set.
   */
  private void setIdStrBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    idStr_ = value.toStringUtf8();

  }

  public static final int LAN_FIELD_NUMBER = 3;
  private java.lang.String lan_;
  /**
   * <pre>
   * 字幕语言code
   * </pre>
   *
   * <code>string lan = 3;</code>
   * @return The lan.
   */
  @java.lang.Override
  public java.lang.String getLan() {
    return lan_;
  }
  /**
   * <pre>
   * 字幕语言code
   * </pre>
   *
   * <code>string lan = 3;</code>
   * @return The bytes for lan.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(lan_);
  }
  /**
   * <pre>
   * 字幕语言code
   * </pre>
   *
   * <code>string lan = 3;</code>
   * @param value The lan to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setLan(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    lan_ = value;
  }
  /**
   * <pre>
   * 字幕语言code
   * </pre>
   *
   * <code>string lan = 3;</code>
   */
  private void clearLan() {

    lan_ = getDefaultInstance().getLan();
  }
  /**
   * <pre>
   * 字幕语言code
   * </pre>
   *
   * <code>string lan = 3;</code>
   * @param value The bytes for lan to set.
   */
  private void setLanBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    lan_ = value.toStringUtf8();

  }

  public static final int LAN_DOC_FIELD_NUMBER = 4;
  private java.lang.String lanDoc_;
  /**
   * <pre>
   * 字幕语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 4;</code>
   * @return The lanDoc.
   */
  @java.lang.Override
  public java.lang.String getLanDoc() {
    return lanDoc_;
  }
  /**
   * <pre>
   * 字幕语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 4;</code>
   * @return The bytes for lanDoc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanDocBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(lanDoc_);
  }
  /**
   * <pre>
   * 字幕语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 4;</code>
   * @param value The lanDoc to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setLanDoc(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    lanDoc_ = value;
  }
  /**
   * <pre>
   * 字幕语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 4;</code>
   */
  private void clearLanDoc() {

    lanDoc_ = getDefaultInstance().getLanDoc();
  }
  /**
   * <pre>
   * 字幕语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 4;</code>
   * @param value The bytes for lanDoc to set.
   */
  private void setLanDocBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    lanDoc_ = value.toStringUtf8();

  }

  public static final int SUBTITLE_URL_FIELD_NUMBER = 5;
  private java.lang.String subtitleUrl_;
  /**
   * <pre>
   * 字幕链接地址
   * </pre>
   *
   * <code>string subtitle_url = 5;</code>
   * @return The subtitleUrl.
   */
  @java.lang.Override
  public java.lang.String getSubtitleUrl() {
    return subtitleUrl_;
  }
  /**
   * <pre>
   * 字幕链接地址
   * </pre>
   *
   * <code>string subtitle_url = 5;</code>
   * @return The bytes for subtitleUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubtitleUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(subtitleUrl_);
  }
  /**
   * <pre>
   * 字幕链接地址
   * </pre>
   *
   * <code>string subtitle_url = 5;</code>
   * @param value The subtitleUrl to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSubtitleUrl(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    subtitleUrl_ = value;
  }
  /**
   * <pre>
   * 字幕链接地址
   * </pre>
   *
   * <code>string subtitle_url = 5;</code>
   */
  private void clearSubtitleUrl() {

    subtitleUrl_ = getDefaultInstance().getSubtitleUrl();
  }
  /**
   * <pre>
   * 字幕链接地址
   * </pre>
   *
   * <code>string subtitle_url = 5;</code>
   * @param value The bytes for subtitleUrl to set.
   */
  private void setSubtitleUrlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    subtitleUrl_ = value.toStringUtf8();

  }

  public static final int AUTHOR_FIELD_NUMBER = 6;
  private com.bapis.bilibili.community.service.dm.v1.UserInfo author_;
  /**
   * <pre>
   * 字幕作者信息
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
   */
  @java.lang.Override
  public boolean hasAuthor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 字幕作者信息
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.UserInfo getAuthor() {
    return author_ == null ? com.bapis.bilibili.community.service.dm.v1.UserInfo.getDefaultInstance() : author_;
  }
  /**
   * <pre>
   * 字幕作者信息
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setAuthor(com.bapis.bilibili.community.service.dm.v1.UserInfo value) {
    value.getClass();  // minimal bytecode null check
    author_ = value;
    bitField0_ |= 0x00000001;
    }
  /**
   * <pre>
   * 字幕作者信息
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality", "ReturnValueIgnored"})
  private void mergeAuthor(com.bapis.bilibili.community.service.dm.v1.UserInfo value) {
    value.getClass();  // minimal bytecode null check
    if (author_ != null &&
        author_ != com.bapis.bilibili.community.service.dm.v1.UserInfo.getDefaultInstance()) {
      author_ =
        com.bapis.bilibili.community.service.dm.v1.UserInfo.newBuilder(author_).mergeFrom(value).buildPartial();
    } else {
      author_ = value;
    }
    bitField0_ |= 0x00000001;
  }
  /**
   * <pre>
   * 字幕作者信息
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
   */
  private void clearAuthor() {  author_ = null;
    bitField0_ = (bitField0_ & ~0x00000001);
  }

  public static final int TYPE_FIELD_NUMBER = 7;
  private int type_;
  /**
   * <pre>
   * 字幕类型
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.SubtitleType type = 7;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override
  public int getTypeValue() {
    return type_;
  }
  /**
   * <pre>
   * 字幕类型
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.SubtitleType type = 7;</code>
   * @return The type.
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.SubtitleType getType() {
    com.bapis.bilibili.community.service.dm.v1.SubtitleType result = com.bapis.bilibili.community.service.dm.v1.SubtitleType.forNumber(type_);
    return result == null ? com.bapis.bilibili.community.service.dm.v1.SubtitleType.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * 字幕类型
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.SubtitleType type = 7;</code>
   * @param value The enum numeric value on the wire for type to set.
   */
  private void setTypeValue(int value) {
      type_ = value;
  }
  /**
   * <pre>
   * 字幕类型
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.SubtitleType type = 7;</code>
   * @param value The type to set.
   */
  private void setType(com.bapis.bilibili.community.service.dm.v1.SubtitleType value) {
    type_ = value.getNumber();

  }
  /**
   * <pre>
   * 字幕类型
   * </pre>
   *
   * <code>.bilibili.community.service.dm.v1.SubtitleType type = 7;</code>
   */
  private void clearType() {

    type_ = 0;
  }

  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.community.service.dm.v1.SubtitleItem prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * SubtitleItem 单个字幕信息
   * </pre>
   *
   * Protobuf type {@code bilibili.community.service.dm.v1.SubtitleItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.bapis.bilibili.community.service.dm.v1.SubtitleItem, Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.community.service.dm.v1.SubtitleItem)
      com.bapis.bilibili.community.service.dm.v1.SubtitleItemOrBuilder {
    // Construct using com.bapis.bilibili.community.service.dm.v1.SubtitleItem.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 字幕id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return instance.getId();
    }
    /**
     * <pre>
     * 字幕id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <pre>
     * 字幕id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    /**
     * <pre>
     * 字幕id string
     * </pre>
     *
     * <code>string id_str = 2;</code>
     * @return The idStr.
     */
    @java.lang.Override
    public java.lang.String getIdStr() {
      return instance.getIdStr();
    }
    /**
     * <pre>
     * 字幕id string
     * </pre>
     *
     * <code>string id_str = 2;</code>
     * @return The bytes for idStr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdStrBytes() {
      return instance.getIdStrBytes();
    }
    /**
     * <pre>
     * 字幕id string
     * </pre>
     *
     * <code>string id_str = 2;</code>
     * @param value The idStr to set.
     * @return This builder for chaining.
     */
    public Builder setIdStr(
        java.lang.String value) {
      copyOnWrite();
      instance.setIdStr(value);
      return this;
    }
    /**
     * <pre>
     * 字幕id string
     * </pre>
     *
     * <code>string id_str = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdStr() {
      copyOnWrite();
      instance.clearIdStr();
      return this;
    }
    /**
     * <pre>
     * 字幕id string
     * </pre>
     *
     * <code>string id_str = 2;</code>
     * @param value The bytes for idStr to set.
     * @return This builder for chaining.
     */
    public Builder setIdStrBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdStrBytes(value);
      return this;
    }

    /**
     * <pre>
     * 字幕语言code
     * </pre>
     *
     * <code>string lan = 3;</code>
     * @return The lan.
     */
    @java.lang.Override
    public java.lang.String getLan() {
      return instance.getLan();
    }
    /**
     * <pre>
     * 字幕语言code
     * </pre>
     *
     * <code>string lan = 3;</code>
     * @return The bytes for lan.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanBytes() {
      return instance.getLanBytes();
    }
    /**
     * <pre>
     * 字幕语言code
     * </pre>
     *
     * <code>string lan = 3;</code>
     * @param value The lan to set.
     * @return This builder for chaining.
     */
    public Builder setLan(
        java.lang.String value) {
      copyOnWrite();
      instance.setLan(value);
      return this;
    }
    /**
     * <pre>
     * 字幕语言code
     * </pre>
     *
     * <code>string lan = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLan() {
      copyOnWrite();
      instance.clearLan();
      return this;
    }
    /**
     * <pre>
     * 字幕语言code
     * </pre>
     *
     * <code>string lan = 3;</code>
     * @param value The bytes for lan to set.
     * @return This builder for chaining.
     */
    public Builder setLanBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLanBytes(value);
      return this;
    }

    /**
     * <pre>
     * 字幕语言中文文案
     * </pre>
     *
     * <code>string lan_doc = 4;</code>
     * @return The lanDoc.
     */
    @java.lang.Override
    public java.lang.String getLanDoc() {
      return instance.getLanDoc();
    }
    /**
     * <pre>
     * 字幕语言中文文案
     * </pre>
     *
     * <code>string lan_doc = 4;</code>
     * @return The bytes for lanDoc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanDocBytes() {
      return instance.getLanDocBytes();
    }
    /**
     * <pre>
     * 字幕语言中文文案
     * </pre>
     *
     * <code>string lan_doc = 4;</code>
     * @param value The lanDoc to set.
     * @return This builder for chaining.
     */
    public Builder setLanDoc(
        java.lang.String value) {
      copyOnWrite();
      instance.setLanDoc(value);
      return this;
    }
    /**
     * <pre>
     * 字幕语言中文文案
     * </pre>
     *
     * <code>string lan_doc = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanDoc() {
      copyOnWrite();
      instance.clearLanDoc();
      return this;
    }
    /**
     * <pre>
     * 字幕语言中文文案
     * </pre>
     *
     * <code>string lan_doc = 4;</code>
     * @param value The bytes for lanDoc to set.
     * @return This builder for chaining.
     */
    public Builder setLanDocBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLanDocBytes(value);
      return this;
    }

    /**
     * <pre>
     * 字幕链接地址
     * </pre>
     *
     * <code>string subtitle_url = 5;</code>
     * @return The subtitleUrl.
     */
    @java.lang.Override
    public java.lang.String getSubtitleUrl() {
      return instance.getSubtitleUrl();
    }
    /**
     * <pre>
     * 字幕链接地址
     * </pre>
     *
     * <code>string subtitle_url = 5;</code>
     * @return The bytes for subtitleUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSubtitleUrlBytes() {
      return instance.getSubtitleUrlBytes();
    }
    /**
     * <pre>
     * 字幕链接地址
     * </pre>
     *
     * <code>string subtitle_url = 5;</code>
     * @param value The subtitleUrl to set.
     * @return This builder for chaining.
     */
    public Builder setSubtitleUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setSubtitleUrl(value);
      return this;
    }
    /**
     * <pre>
     * 字幕链接地址
     * </pre>
     *
     * <code>string subtitle_url = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearSubtitleUrl() {
      copyOnWrite();
      instance.clearSubtitleUrl();
      return this;
    }
    /**
     * <pre>
     * 字幕链接地址
     * </pre>
     *
     * <code>string subtitle_url = 5;</code>
     * @param value The bytes for subtitleUrl to set.
     * @return This builder for chaining.
     */
    public Builder setSubtitleUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSubtitleUrlBytes(value);
      return this;
    }

    /**
     * <pre>
     * 字幕作者信息
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
     */
    @java.lang.Override
    public boolean hasAuthor() {
      return instance.hasAuthor();
    }
    /**
     * <pre>
     * 字幕作者信息
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.UserInfo getAuthor() {
      return instance.getAuthor();
    }
    /**
     * <pre>
     * 字幕作者信息
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
     */
    public Builder setAuthor(com.bapis.bilibili.community.service.dm.v1.UserInfo value) {
      copyOnWrite();
      instance.setAuthor(value);
      return this;
      }
    /**
     * <pre>
     * 字幕作者信息
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
     */
    public Builder setAuthor(
        com.bapis.bilibili.community.service.dm.v1.UserInfo.Builder builderForValue) {
      copyOnWrite();
      instance.setAuthor(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 字幕作者信息
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
     */
    public Builder mergeAuthor(com.bapis.bilibili.community.service.dm.v1.UserInfo value) {
      copyOnWrite();
      instance.mergeAuthor(value);
      return this;
    }
    /**
     * <pre>
     * 字幕作者信息
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.UserInfo author = 6;</code>
     */
    public Builder clearAuthor() {  copyOnWrite();
      instance.clearAuthor();
      return this;
    }

    /**
     * <pre>
     * 字幕类型
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.SubtitleType type = 7;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override
    public int getTypeValue() {
      return instance.getTypeValue();
    }
    /**
     * <pre>
     * 字幕类型
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.SubtitleType type = 7;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      copyOnWrite();
      instance.setTypeValue(value);
      return this;
    }
    /**
     * <pre>
     * 字幕类型
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.SubtitleType type = 7;</code>
     * @return The type.
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.SubtitleType getType() {
      return instance.getType();
    }
    /**
     * <pre>
     * 字幕类型
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.SubtitleType type = 7;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setType(com.bapis.bilibili.community.service.dm.v1.SubtitleType value) {
      copyOnWrite();
      instance.setType(value);
      return this;
    }
    /**
     * <pre>
     * 字幕类型
     * </pre>
     *
     * <code>.bilibili.community.service.dm.v1.SubtitleType type = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      copyOnWrite();
      instance.clearType();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.community.service.dm.v1.SubtitleItem)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.bapis.bilibili.community.service.dm.v1.SubtitleItem();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "bitField0_",
            "id_",
            "idStr_",
            "lan_",
            "lanDoc_",
            "subtitleUrl_",
            "author_",
            "type_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0001\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0002\u0002\u0208" +
              "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u1009\u0000\u0007\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.bapis.bilibili.community.service.dm.v1.SubtitleItem> parser = PARSER;
        if (parser == null) {
          synchronized (com.bapis.bilibili.community.service.dm.v1.SubtitleItem.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.bapis.bilibili.community.service.dm.v1.SubtitleItem>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bilibili.community.service.dm.v1.SubtitleItem)
  private static final com.bapis.bilibili.community.service.dm.v1.SubtitleItem DEFAULT_INSTANCE;
  static {
    SubtitleItem defaultInstance = new SubtitleItem();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      SubtitleItem.class, defaultInstance);
  }

  public static com.bapis.bilibili.community.service.dm.v1.SubtitleItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SubtitleItem> PARSER;

  public static com.google.protobuf.Parser<SubtitleItem> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

