// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

/**
 * <pre>
 * SubtitleType 字幕类型
 * </pre>
 *
 * Protobuf enum {@code bilibili.community.service.dm.v1.SubtitleType}
 */
public enum SubtitleType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   * cc字幕
   * </pre>
   *
   * <code>CC = 0;</code>
   */
  CC(0),
  /**
   * <pre>
   * 智能字幕
   * </pre>
   *
   * <code>AI = 1;</code>
   */
  AI(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * cc字幕
   * </pre>
   *
   * <code>CC = 0;</code>
   */
  public static final int CC_VALUE = 0;
  /**
   * <pre>
   * 智能字幕
   * </pre>
   *
   * <code>AI = 1;</code>
   */
  public static final int AI_VALUE = 1;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static SubtitleType valueOf(int value) {
    return forNumber(value);
  }

  public static SubtitleType forNumber(int value) {
    switch (value) {
      case 0: return CC;
      case 1: return AI;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<SubtitleType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      SubtitleType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<SubtitleType>() {
          @java.lang.Override
          public SubtitleType findValueByNumber(int number) {
            return SubtitleType.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return SubtitleTypeVerifier.INSTANCE;
  }

  private static final class SubtitleTypeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new SubtitleTypeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return SubtitleType.forNumber(number) != null;
          }
        };

  private final int value;

  private SubtitleType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:bilibili.community.service.dm.v1.SubtitleType)
}

