// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

/**
 * <pre>
 * VideoSubtitle 视频字幕
 * </pre>
 *
 * Protobuf type {@code bilibili.community.service.dm.v1.VideoSubtitle}
 */
public  final class VideoSubtitle extends
    com.google.protobuf.GeneratedMessageLite<
        VideoSubtitle, VideoSubtitle.Builder> implements
    // @@protoc_insertion_point(message_implements:bilibili.community.service.dm.v1.VideoSubtitle)
    VideoSubtitleOrBuilder {
  private VideoSubtitle() {
    lan_ = "";
    lanDoc_ = "";
    subtitles_ = emptyProtobufList();
  }
  public static final int LAN_FIELD_NUMBER = 1;
  private java.lang.String lan_;
  /**
   * <pre>
   * 视频的原文语言code
   * </pre>
   *
   * <code>string lan = 1;</code>
   * @return The lan.
   */
  @java.lang.Override
  public java.lang.String getLan() {
    return lan_;
  }
  /**
   * <pre>
   * 视频的原文语言code
   * </pre>
   *
   * <code>string lan = 1;</code>
   * @return The bytes for lan.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(lan_);
  }
  /**
   * <pre>
   * 视频的原文语言code
   * </pre>
   *
   * <code>string lan = 1;</code>
   * @param value The lan to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setLan(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    lan_ = value;
  }
  /**
   * <pre>
   * 视频的原文语言code
   * </pre>
   *
   * <code>string lan = 1;</code>
   */
  private void clearLan() {

    lan_ = getDefaultInstance().getLan();
  }
  /**
   * <pre>
   * 视频的原文语言code
   * </pre>
   *
   * <code>string lan = 1;</code>
   * @param value The bytes for lan to set.
   */
  private void setLanBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    lan_ = value.toStringUtf8();

  }

  public static final int LAN_DOC_FIELD_NUMBER = 2;
  private java.lang.String lanDoc_;
  /**
   * <pre>
   * 视频的原文语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 2;</code>
   * @return The lanDoc.
   */
  @java.lang.Override
  public java.lang.String getLanDoc() {
    return lanDoc_;
  }
  /**
   * <pre>
   * 视频的原文语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 2;</code>
   * @return The bytes for lanDoc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanDocBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(lanDoc_);
  }
  /**
   * <pre>
   * 视频的原文语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 2;</code>
   * @param value The lanDoc to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setLanDoc(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    lanDoc_ = value;
  }
  /**
   * <pre>
   * 视频的原文语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 2;</code>
   */
  private void clearLanDoc() {

    lanDoc_ = getDefaultInstance().getLanDoc();
  }
  /**
   * <pre>
   * 视频的原文语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 2;</code>
   * @param value The bytes for lanDoc to set.
   */
  private void setLanDocBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    lanDoc_ = value.toStringUtf8();

  }

  public static final int SUBTITLES_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<com.bapis.bilibili.community.service.dm.v1.SubtitleItem> subtitles_;
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.bapis.bilibili.community.service.dm.v1.SubtitleItem> getSubtitlesList() {
    return subtitles_;
  }
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  public java.util.List<? extends com.bapis.bilibili.community.service.dm.v1.SubtitleItemOrBuilder> 
      getSubtitlesOrBuilderList() {
    return subtitles_;
  }
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  @java.lang.Override
  public int getSubtitlesCount() {
    return subtitles_.size();
  }
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  @java.lang.Override
  public com.bapis.bilibili.community.service.dm.v1.SubtitleItem getSubtitles(int index) {
    return subtitles_.get(index);
  }
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  public com.bapis.bilibili.community.service.dm.v1.SubtitleItemOrBuilder getSubtitlesOrBuilder(
      int index) {
    return subtitles_.get(index);
  }
  private void ensureSubtitlesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<com.bapis.bilibili.community.service.dm.v1.SubtitleItem> tmp = subtitles_;
    if (!tmp.isModifiable()) {
      subtitles_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setSubtitles(
      int index, com.bapis.bilibili.community.service.dm.v1.SubtitleItem value) {
    value.getClass();  // minimal bytecode null check
    ensureSubtitlesIsMutable();
    subtitles_.set(index, value);
  }
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addSubtitles(com.bapis.bilibili.community.service.dm.v1.SubtitleItem value) {
    value.getClass();  // minimal bytecode null check
    ensureSubtitlesIsMutable();
    subtitles_.add(value);
  }
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void addSubtitles(
      int index, com.bapis.bilibili.community.service.dm.v1.SubtitleItem value) {
    value.getClass();  // minimal bytecode null check
    ensureSubtitlesIsMutable();
    subtitles_.add(index, value);
  }
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  private void addAllSubtitles(
      java.lang.Iterable<? extends com.bapis.bilibili.community.service.dm.v1.SubtitleItem> values) {
    ensureSubtitlesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, subtitles_);
  }
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  private void clearSubtitles() {
    subtitles_ = emptyProtobufList();
  }
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  private void removeSubtitles(int index) {
    ensureSubtitlesIsMutable();
    subtitles_.remove(index);
  }

  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.community.service.dm.v1.VideoSubtitle prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * VideoSubtitle 视频字幕
   * </pre>
   *
   * Protobuf type {@code bilibili.community.service.dm.v1.VideoSubtitle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.bapis.bilibili.community.service.dm.v1.VideoSubtitle, Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.community.service.dm.v1.VideoSubtitle)
      com.bapis.bilibili.community.service.dm.v1.VideoSubtitleOrBuilder {
    // Construct using com.bapis.bilibili.community.service.dm.v1.VideoSubtitle.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 视频的原文语言code
     * </pre>
     *
     * <code>string lan = 1;</code>
     * @return The lan.
     */
    @java.lang.Override
    public java.lang.String getLan() {
      return instance.getLan();
    }
    /**
     * <pre>
     * 视频的原文语言code
     * </pre>
     *
     * <code>string lan = 1;</code>
     * @return The bytes for lan.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanBytes() {
      return instance.getLanBytes();
    }
    /**
     * <pre>
     * 视频的原文语言code
     * </pre>
     *
     * <code>string lan = 1;</code>
     * @param value The lan to set.
     * @return This builder for chaining.
     */
    public Builder setLan(
        java.lang.String value) {
      copyOnWrite();
      instance.setLan(value);
      return this;
    }
    /**
     * <pre>
     * 视频的原文语言code
     * </pre>
     *
     * <code>string lan = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLan() {
      copyOnWrite();
      instance.clearLan();
      return this;
    }
    /**
     * <pre>
     * 视频的原文语言code
     * </pre>
     *
     * <code>string lan = 1;</code>
     * @param value The bytes for lan to set.
     * @return This builder for chaining.
     */
    public Builder setLanBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLanBytes(value);
      return this;
    }

    /**
     * <pre>
     * 视频的原文语言中文文案
     * </pre>
     *
     * <code>string lan_doc = 2;</code>
     * @return The lanDoc.
     */
    @java.lang.Override
    public java.lang.String getLanDoc() {
      return instance.getLanDoc();
    }
    /**
     * <pre>
     * 视频的原文语言中文文案
     * </pre>
     *
     * <code>string lan_doc = 2;</code>
     * @return The bytes for lanDoc.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLanDocBytes() {
      return instance.getLanDocBytes();
    }
    /**
     * <pre>
     * 视频的原文语言中文文案
     * </pre>
     *
     * <code>string lan_doc = 2;</code>
     * @param value The lanDoc to set.
     * @return This builder for chaining.
     */
    public Builder setLanDoc(
        java.lang.String value) {
      copyOnWrite();
      instance.setLanDoc(value);
      return this;
    }
    /**
     * <pre>
     * 视频的原文语言中文文案
     * </pre>
     *
     * <code>string lan_doc = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanDoc() {
      copyOnWrite();
      instance.clearLanDoc();
      return this;
    }
    /**
     * <pre>
     * 视频的原文语言中文文案
     * </pre>
     *
     * <code>string lan_doc = 2;</code>
     * @param value The bytes for lanDoc to set.
     * @return This builder for chaining.
     */
    public Builder setLanDocBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setLanDocBytes(value);
      return this;
    }

    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.bapis.bilibili.community.service.dm.v1.SubtitleItem> getSubtitlesList() {
      return java.util.Collections.unmodifiableList(
          instance.getSubtitlesList());
    }
    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    @java.lang.Override
    public int getSubtitlesCount() {
      return instance.getSubtitlesCount();
    }/**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    @java.lang.Override
    public com.bapis.bilibili.community.service.dm.v1.SubtitleItem getSubtitles(int index) {
      return instance.getSubtitles(index);
    }
    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    public Builder setSubtitles(
        int index, com.bapis.bilibili.community.service.dm.v1.SubtitleItem value) {
      copyOnWrite();
      instance.setSubtitles(index, value);
      return this;
    }
    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    public Builder setSubtitles(
        int index, com.bapis.bilibili.community.service.dm.v1.SubtitleItem.Builder builderForValue) {
      copyOnWrite();
      instance.setSubtitles(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    public Builder addSubtitles(com.bapis.bilibili.community.service.dm.v1.SubtitleItem value) {
      copyOnWrite();
      instance.addSubtitles(value);
      return this;
    }
    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    public Builder addSubtitles(
        int index, com.bapis.bilibili.community.service.dm.v1.SubtitleItem value) {
      copyOnWrite();
      instance.addSubtitles(index, value);
      return this;
    }
    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    public Builder addSubtitles(
        com.bapis.bilibili.community.service.dm.v1.SubtitleItem.Builder builderForValue) {
      copyOnWrite();
      instance.addSubtitles(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    public Builder addSubtitles(
        int index, com.bapis.bilibili.community.service.dm.v1.SubtitleItem.Builder builderForValue) {
      copyOnWrite();
      instance.addSubtitles(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    public Builder addAllSubtitles(
        java.lang.Iterable<? extends com.bapis.bilibili.community.service.dm.v1.SubtitleItem> values) {
      copyOnWrite();
      instance.addAllSubtitles(values);
      return this;
    }
    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    public Builder clearSubtitles() {
      copyOnWrite();
      instance.clearSubtitles();
      return this;
    }
    /**
     * <pre>
     * 视频下的字幕文件
     * </pre>
     *
     * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
     */
    public Builder removeSubtitles(int index) {
      copyOnWrite();
      instance.removeSubtitles(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.community.service.dm.v1.VideoSubtitle)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.bapis.bilibili.community.service.dm.v1.VideoSubtitle();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "lan_",
            "lanDoc_",
            "subtitles_",
            com.bapis.bilibili.community.service.dm.v1.SubtitleItem.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.bapis.bilibili.community.service.dm.v1.VideoSubtitle> parser = PARSER;
        if (parser == null) {
          synchronized (com.bapis.bilibili.community.service.dm.v1.VideoSubtitle.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.bapis.bilibili.community.service.dm.v1.VideoSubtitle>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bilibili.community.service.dm.v1.VideoSubtitle)
  private static final com.bapis.bilibili.community.service.dm.v1.VideoSubtitle DEFAULT_INSTANCE;
  static {
    VideoSubtitle defaultInstance = new VideoSubtitle();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      VideoSubtitle.class, defaultInstance);
  }

  public static com.bapis.bilibili.community.service.dm.v1.VideoSubtitle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<VideoSubtitle> PARSER;

  public static com.google.protobuf.Parser<VideoSubtitle> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

