// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

public interface VideoSubtitleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bilibili.community.service.dm.v1.VideoSubtitle)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * 视频的原文语言code
   * </pre>
   *
   * <code>string lan = 1;</code>
   * @return The lan.
   */
  java.lang.String getLan();
  /**
   * <pre>
   * 视频的原文语言code
   * </pre>
   *
   * <code>string lan = 1;</code>
   * @return The bytes for lan.
   */
  com.google.protobuf.ByteString
      getLanBytes();

  /**
   * <pre>
   * 视频的原文语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 2;</code>
   * @return The lanDoc.
   */
  java.lang.String getLanDoc();
  /**
   * <pre>
   * 视频的原文语言中文文案
   * </pre>
   *
   * <code>string lan_doc = 2;</code>
   * @return The bytes for lanDoc.
   */
  com.google.protobuf.ByteString
      getLanDocBytes();

  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  java.util.List<com.bapis.bilibili.community.service.dm.v1.SubtitleItem> 
      getSubtitlesList();
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  com.bapis.bilibili.community.service.dm.v1.SubtitleItem getSubtitles(int index);
  /**
   * <pre>
   * 视频下的字幕文件
   * </pre>
   *
   * <code>repeated .bilibili.community.service.dm.v1.SubtitleItem subtitles = 3;</code>
   */
  int getSubtitlesCount();
}
