// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bilibili/community/service/dm/v1/dm.proto
// Protobuf Java Version: 4.29.0

package com.bapis.bilibili.community.service.dm.v1;

/**
 * <pre>
 * VideoMask 视频弹幕蒙版
 * </pre>
 *
 * Protobuf type {@code bilibili.community.service.dm.v1.VideoMask}
 */
public  final class VideoMask extends
    com.google.protobuf.GeneratedMessageLite<
        VideoMask, VideoMask.Builder> implements
    // @@protoc_insertion_point(message_implements:bilibili.community.service.dm.v1.VideoMask)
    VideoMaskOrBuilder {
  private VideoMask() {
    maskUrl_ = "";
  }
  public static final int CID_FIELD_NUMBER = 1;
  private long cid_;
  /**
   * <pre>
   * 视频cid
   * </pre>
   *
   * <code>int64 cid = 1;</code>
   * @return The cid.
   */
  @java.lang.Override
  public long getCid() {
    return cid_;
  }
  /**
   * <pre>
   * 视频cid
   * </pre>
   *
   * <code>int64 cid = 1;</code>
   * @param value The cid to set.
   */
  private void setCid(long value) {
    
    cid_ = value;
  }
  /**
   * <pre>
   * 视频cid
   * </pre>
   *
   * <code>int64 cid = 1;</code>
   */
  private void clearCid() {

    cid_ = 0L;
  }

  public static final int PLAT_FIELD_NUMBER = 2;
  private int plat_;
  /**
   * <pre>
   * 平台 0为网页端，1为移动端
   * </pre>
   *
   * <code>int32 plat = 2;</code>
   * @return The plat.
   */
  @java.lang.Override
  public int getPlat() {
    return plat_;
  }
  /**
   * <pre>
   * 平台 0为网页端，1为移动端
   * </pre>
   *
   * <code>int32 plat = 2;</code>
   * @param value The plat to set.
   */
  private void setPlat(int value) {
    
    plat_ = value;
  }
  /**
   * <pre>
   * 平台 0为网页端，1为移动端
   * </pre>
   *
   * <code>int32 plat = 2;</code>
   */
  private void clearPlat() {

    plat_ = 0;
  }

  public static final int FPS_FIELD_NUMBER = 3;
  private int fps_;
  /**
   * <pre>
   * 视频帧率
   * </pre>
   *
   * <code>int32 fps = 3;</code>
   * @return The fps.
   */
  @java.lang.Override
  public int getFps() {
    return fps_;
  }
  /**
   * <pre>
   * 视频帧率
   * </pre>
   *
   * <code>int32 fps = 3;</code>
   * @param value The fps to set.
   */
  private void setFps(int value) {
    
    fps_ = value;
  }
  /**
   * <pre>
   * 视频帧率
   * </pre>
   *
   * <code>int32 fps = 3;</code>
   */
  private void clearFps() {

    fps_ = 0;
  }

  public static final int TIME_FIELD_NUMBER = 4;
  private long time_;
  /**
   * <pre>
   * 间隔时间
   * </pre>
   *
   * <code>int64 time = 4;</code>
   * @return The time.
   */
  @java.lang.Override
  public long getTime() {
    return time_;
  }
  /**
   * <pre>
   * 间隔时间
   * </pre>
   *
   * <code>int64 time = 4;</code>
   * @param value The time to set.
   */
  private void setTime(long value) {
    
    time_ = value;
  }
  /**
   * <pre>
   * 间隔时间
   * </pre>
   *
   * <code>int64 time = 4;</code>
   */
  private void clearTime() {

    time_ = 0L;
  }

  public static final int MASK_URL_FIELD_NUMBER = 5;
  private java.lang.String maskUrl_;
  /**
   * <pre>
   * 弹幕蒙版地址链接
   * </pre>
   *
   * <code>string mask_url = 5;</code>
   * @return The maskUrl.
   */
  @java.lang.Override
  public java.lang.String getMaskUrl() {
    return maskUrl_;
  }
  /**
   * <pre>
   * 弹幕蒙版地址链接
   * </pre>
   *
   * <code>string mask_url = 5;</code>
   * @return The bytes for maskUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMaskUrlBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(maskUrl_);
  }
  /**
   * <pre>
   * 弹幕蒙版地址链接
   * </pre>
   *
   * <code>string mask_url = 5;</code>
   * @param value The maskUrl to set.
   */
  @java.lang.SuppressWarnings("ReturnValueIgnored")
  private void setMaskUrl(
      java.lang.String value) {
    value.getClass();  // minimal bytecode null check

    maskUrl_ = value;
  }
  /**
   * <pre>
   * 弹幕蒙版地址链接
   * </pre>
   *
   * <code>string mask_url = 5;</code>
   */
  private void clearMaskUrl() {

    maskUrl_ = getDefaultInstance().getMaskUrl();
  }
  /**
   * <pre>
   * 弹幕蒙版地址链接
   * </pre>
   *
   * <code>string mask_url = 5;</code>
   * @param value The bytes for maskUrl to set.
   */
  private void setMaskUrlBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    maskUrl_ = value.toStringUtf8();

  }

  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.bapis.bilibili.community.service.dm.v1.VideoMask parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.bapis.bilibili.community.service.dm.v1.VideoMask prototype) {
    return DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * VideoMask 视频弹幕蒙版
   * </pre>
   *
   * Protobuf type {@code bilibili.community.service.dm.v1.VideoMask}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.bapis.bilibili.community.service.dm.v1.VideoMask, Builder> implements
      // @@protoc_insertion_point(builder_implements:bilibili.community.service.dm.v1.VideoMask)
      com.bapis.bilibili.community.service.dm.v1.VideoMaskOrBuilder {
    // Construct using com.bapis.bilibili.community.service.dm.v1.VideoMask.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 视频cid
     * </pre>
     *
     * <code>int64 cid = 1;</code>
     * @return The cid.
     */
    @java.lang.Override
    public long getCid() {
      return instance.getCid();
    }
    /**
     * <pre>
     * 视频cid
     * </pre>
     *
     * <code>int64 cid = 1;</code>
     * @param value The cid to set.
     * @return This builder for chaining.
     */
    public Builder setCid(long value) {
      copyOnWrite();
      instance.setCid(value);
      return this;
    }
    /**
     * <pre>
     * 视频cid
     * </pre>
     *
     * <code>int64 cid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCid() {
      copyOnWrite();
      instance.clearCid();
      return this;
    }

    /**
     * <pre>
     * 平台 0为网页端，1为移动端
     * </pre>
     *
     * <code>int32 plat = 2;</code>
     * @return The plat.
     */
    @java.lang.Override
    public int getPlat() {
      return instance.getPlat();
    }
    /**
     * <pre>
     * 平台 0为网页端，1为移动端
     * </pre>
     *
     * <code>int32 plat = 2;</code>
     * @param value The plat to set.
     * @return This builder for chaining.
     */
    public Builder setPlat(int value) {
      copyOnWrite();
      instance.setPlat(value);
      return this;
    }
    /**
     * <pre>
     * 平台 0为网页端，1为移动端
     * </pre>
     *
     * <code>int32 plat = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlat() {
      copyOnWrite();
      instance.clearPlat();
      return this;
    }

    /**
     * <pre>
     * 视频帧率
     * </pre>
     *
     * <code>int32 fps = 3;</code>
     * @return The fps.
     */
    @java.lang.Override
    public int getFps() {
      return instance.getFps();
    }
    /**
     * <pre>
     * 视频帧率
     * </pre>
     *
     * <code>int32 fps = 3;</code>
     * @param value The fps to set.
     * @return This builder for chaining.
     */
    public Builder setFps(int value) {
      copyOnWrite();
      instance.setFps(value);
      return this;
    }
    /**
     * <pre>
     * 视频帧率
     * </pre>
     *
     * <code>int32 fps = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFps() {
      copyOnWrite();
      instance.clearFps();
      return this;
    }

    /**
     * <pre>
     * 间隔时间
     * </pre>
     *
     * <code>int64 time = 4;</code>
     * @return The time.
     */
    @java.lang.Override
    public long getTime() {
      return instance.getTime();
    }
    /**
     * <pre>
     * 间隔时间
     * </pre>
     *
     * <code>int64 time = 4;</code>
     * @param value The time to set.
     * @return This builder for chaining.
     */
    public Builder setTime(long value) {
      copyOnWrite();
      instance.setTime(value);
      return this;
    }
    /**
     * <pre>
     * 间隔时间
     * </pre>
     *
     * <code>int64 time = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTime() {
      copyOnWrite();
      instance.clearTime();
      return this;
    }

    /**
     * <pre>
     * 弹幕蒙版地址链接
     * </pre>
     *
     * <code>string mask_url = 5;</code>
     * @return The maskUrl.
     */
    @java.lang.Override
    public java.lang.String getMaskUrl() {
      return instance.getMaskUrl();
    }
    /**
     * <pre>
     * 弹幕蒙版地址链接
     * </pre>
     *
     * <code>string mask_url = 5;</code>
     * @return The bytes for maskUrl.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMaskUrlBytes() {
      return instance.getMaskUrlBytes();
    }
    /**
     * <pre>
     * 弹幕蒙版地址链接
     * </pre>
     *
     * <code>string mask_url = 5;</code>
     * @param value The maskUrl to set.
     * @return This builder for chaining.
     */
    public Builder setMaskUrl(
        java.lang.String value) {
      copyOnWrite();
      instance.setMaskUrl(value);
      return this;
    }
    /**
     * <pre>
     * 弹幕蒙版地址链接
     * </pre>
     *
     * <code>string mask_url = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaskUrl() {
      copyOnWrite();
      instance.clearMaskUrl();
      return this;
    }
    /**
     * <pre>
     * 弹幕蒙版地址链接
     * </pre>
     *
     * <code>string mask_url = 5;</code>
     * @param value The bytes for maskUrl to set.
     * @return This builder for chaining.
     */
    public Builder setMaskUrlBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMaskUrlBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:bilibili.community.service.dm.v1.VideoMask)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.bapis.bilibili.community.service.dm.v1.VideoMask();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "cid_",
            "plat_",
            "fps_",
            "time_",
            "maskUrl_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0002\u0002\u0004" +
              "\u0003\u0004\u0004\u0002\u0005\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.bapis.bilibili.community.service.dm.v1.VideoMask> parser = PARSER;
        if (parser == null) {
          synchronized (com.bapis.bilibili.community.service.dm.v1.VideoMask.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.bapis.bilibili.community.service.dm.v1.VideoMask>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:bilibili.community.service.dm.v1.VideoMask)
  private static final com.bapis.bilibili.community.service.dm.v1.VideoMask DEFAULT_INSTANCE;
  static {
    VideoMask defaultInstance = new VideoMask();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      VideoMask.class, defaultInstance);
  }

  public static com.bapis.bilibili.community.service.dm.v1.VideoMask getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<VideoMask> PARSER;

  public static com.google.protobuf.Parser<VideoMask> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

